### ISSUE TITLE
The starter level tiles are bugged

### ISSUE THREAD

**Issue by AppleC4T** [fossasia/labyrinth#1026]
## Expected Behavior

The tiles should be aligned properly

## Current Behavior

The tiles in the starter level are bugged, it's an issue only with the starter tiles (the tiles that have the syntax `door.{tile}`), as the tile from `dark` const is aligned correctly.
## Possible Solution

Check the syntax, the rendering order and check if the tiles have been rescaled properly in previous PR.

## Steps to Reproduce (for bugs)

1. Open the game
2. Start a new run
3. Try walking around

## Screenshot
![image](https://user-images.githubusercontent.com/34106174/49752573-0b12ea00-fcb1-11e8-9c54-e49aeda5c0f2.png)

**Comment by saarthakchats** [comment]
Tiles are floating, issue must be solved quickly.

**Comment by abishekvashok** [comment]
Applies to all levels as well, possible issue with a tile placer function

**Comment by niccokunzmann** [comment]
There is https://github.com/fossasia/labyrinth/commit/d7acfcd4d7e7deb15a175725db6236b22c0cd026 which resizes many images.

**Comment by YashKumarVerma** [comment]
This issue is solved in #1045
