### ISSUE TITLE
Missing wall between rooms

### ISSUE THREAD

**Issue by jakubpawlina** [fossasia/labyrinth#1032]
## Expected Behavior

Rooms separated by a wall.

## Current Behavior

There is no wall between rooms and it there is a problem which tile should be displayed.
### Screenshot
![zrzut ekranu 146](https://user-images.githubusercontent.com/29257057/49944893-d63ea700-feeb-11e8-8d5f-16447a6e18d2.png)
![zrzut ekranu 148](https://user-images.githubusercontent.com/29257057/49945450-38e47280-feed-11e8-8d42-9444c2b156ee.png)
![zrzut ekranu 147](https://user-images.githubusercontent.com/29257057/49945467-3bdf6300-feed-11e8-864d-3e0458d385b1.png)

## Possible Solution

The tile should be added in room and changed which wall should be displayed

## Context

It doesn't look well

**Comment by Sangatdas** [comment]
Can someone assign this issue to me?

**Comment by abishekvashok** [comment]
Sure go on :)

**Comment by YashKumarVerma** [comment]
Are there any updates @Sangatdas ?
