### ISSUE TITLE
Game is not working

### ISSUE THREAD

**Issue by STEdirisuriya** [fossasia/labyrinth#1033]
## Current Behavior
![image](https://user-images.githubusercontent.com/33794760/50022726-26f4f380-0003-11e9-8bff-a29e0717710b.png)
No tiles will open!

Opened to all

**Comment by AppleC4T** [comment]
I also noticed this recently. It's caused by a simple syntax error and a fix for this is already included in #1029 . Once the PR is merged the bug should be gone

**Comment by niccokunzmann** [comment]
merged, works.
