### ISSUE TITLE
Laguage Selection should be asked on loading of page rather than keeping on top bar

### ISSUE THREAD

**Issue by Sangatdas** [fossasia/labyrinth#1034]
### How to use the Feature
Users will be able to select a language prior starting the game. This way if someone doesn't know English at all, the user will be able to change it in the beginning itself.

### How the Feature Improves the Game
This feature improves usability and understanding of the game for users who don't know English which is default.

### Implementation/Solution Ideas
We can use an overlay on loading of page containing options of selecting the language in the form a selection list.

### Would you like to work on this
Yes

**Comment by abishekvashok** [comment]
> Users will be able to select a language prior starting the game. This way if someone doesn't know English at all, the user will be able to change it in the beginning itself

Please let's just stick to English.

**Comment by Sangatdas** [comment]
@abishekvashok Yes, only an option will be given to the users at the beginning itself. Else the default language will be english.
