### ISSUE TITLE
The Navigation bar displace contents when we switch to 'Tamil and Sinhala'

### ISSUE THREAD

**Issue by ShubhamChaudharyy** [fossasia/labyrinth#1055]
## Current Behavior
![Screenshot (130)](https://user-images.githubusercontent.com/43263087/66600193-a111ec80-ebc2-11e9-813d-61d6a8818aec.png)
## Expected Behavior for Tamil
![Screenshot (131)](https://user-images.githubusercontent.com/43263087/66600253-c141ab80-ebc2-11e9-8edb-44c68860cb8b.png)

## Steps to Reproduce (for bugs)
Change The Language to sinhala or Tamil.

**Comment by xeon-zolt** [comment]
I was not able to reproduce it what is your screen resolution ?
![Peek 2019-10-11 11-30](https://user-images.githubusercontent.com/4529442/66627853-908d6080-ec1a-11e9-9709-0a397662bbe1.gif)
