### ISSUE TITLE
Make added tiles appear in the game

### ISSUE THREAD

**Issue by Ploypiti** [fossasia/labyrinth#106]
### Expected results

All of the added tiles appear in the actual game interface.

![image](https://user-images.githubusercontent.com/32614202/34485915-988219f2-efff-11e7-8947-dffdacd0d792.png)

### Actual results

Not all added tiles appear when moving to a new level.

![image](https://user-images.githubusercontent.com/32614202/34485948-c441a4b8-efff-11e7-9b12-17039523ad30.png)

## Would you like to work on this
Yep

**Comment by niccokunzmann** [comment]
@Ploypiti Can you check if this can be closed?
