### ISSUE TITLE
Inventory for Player

### ISSUE THREAD

**Issue by YashKumarVerma** [fossasia/labyrinth#108]
### Expected results
- Ability to collect items in the game and use them

### Actual results
- Completely isolated player

### Steps to reproduce the issue
- Adding inventory mechanism to game

## Would you like to work on this
- YES 

*after approval*

**Comment by niccokunzmann** [comment]
sounds good to me. How would you like to go about it?

**Comment by YashKumarVerma** [comment]
Add data member to the user object. then store things as array.

**Comment by niccokunzmann** [comment]
Yes, this sounds good. Please never access the inventory directly from
tiles to add objects but use methods like player.addToInventory and
player.hasInInventory to access the content.
https://en.wikipedia.org/wiki/Law_of_Demeter

**Comment by YashKumarVerma** [comment]
![image](https://user-images.githubusercontent.com/14032427/34499298-63df169c-f02b-11e7-9521-ed34c92955ae.png)
😆 did somewhat the same
