### ISSUE TITLE
Show inventory content

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/labyrinth#111]
### Expected results
I would like to know what the player has in the inventory #108 .

### Actual results
I can not see this on the GUI.

Implementation ideas:
- add a new item class which takes a name: a class will allow us to extend it in the future to add item abilities like combinations etc.
- There is a inventory folder with pictures to use for the items. the item loads the picture from that folder.
- when the item is added to the inventory, it is shown, when the item is removed from the inventory, it is removed from the display
- a player can not put the identical item twice into the inventory
- please use the treasure box and key tile to test this functionality

**Comment by YashKumarVerma** [comment]
what's the second point about ? `picture derived from means` ?

**Comment by YashKumarVerma** [comment]
I can work on it

**Comment by niccokunzmann** [comment]
@YashKumarVerma You can work on it. I changed the second point.

**Comment by YashKumarVerma** [comment]
Work in Progress 🔥 
![image](https://user-images.githubusercontent.com/14032427/34558092-995358be-f162-11e7-8140-b0c87ebd5de9.png)

**Comment by YashKumarVerma** [comment]
![image](https://user-images.githubusercontent.com/14032427/34558120-cd1b1a1a-f162-11e7-96bd-f79d54b6ce2f.png)
