### ISSUE TITLE
Dimensions

### ISSUE THREAD

**Issue by samyakbvs** [fossasia/labyrinth#115]
batcave.svg is not in the correct dimensions 
I am working on it

**Comment by niccokunzmann** [comment]
Maybe it is also something with the rendering: The ground is rendered above the walls. Happy coding!

**Comment by YashKumarVerma** [comment]
Please change title to something a bit more descriptive

**Comment by niccokunzmann** [comment]
@samyakbvs Is this working now? I think, we have this resized. All tiles in the labyrinth are resized. Would you close this? I will close it in case no answer comes in three days.

**Comment by abishekvashok** [comment]
@samyakbvs Is this working now? I think, we have this resized. Can we close this?
