### ISSUE TITLE
Build UI

### ISSUE THREAD

**Issue by YashKumarVerma** [fossasia/labyrinth#120]
### Expected results
An interface with systematic buttons and content

### Actual results
![image](https://user-images.githubusercontent.com/14032427/34535552-3d5e90b6-f0e8-11e7-8b69-796bb2b9f229.png)

### Steps to reproduce the issue
- Add buttons and other required items to make the game look systematic

## Would you like to work on this
Yes

**Comment by niccokunzmann** [comment]
Could you elaborate more on what you mean with systematic? Would it be
styling, text, resturcturing? Which buttons do you mean? Just adding
buttons for a "systematic" impression without behavior will not improve
game-play. What do you have in mind?
Do you think about adding a stylesheet to have all buttons of the game
styled?

**Comment by YashKumarVerma** [comment]
@niccokunzmann  The motive is to gave the game an interface which it currently lacks. The same can be easily understood seeing the PR #123
