### ISSUE TITLE
Controls disappear automatically

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/labyrinth#132]
### Expected results

I would like to switch on the controls and remove them manually.

### Actual results

After some time, e.g. when a dialog pop up, the controls disappear.

### Steps to reproduce the issue

1. In the bottom right corner click the running person.
2. the controls open
3. wait some time or navigate
4. the controls disappear

If you also think they should stay so we can play the game with touch, you can solve this :)

**Comment by 0x48piraj** [comment]
I'll take a try :+1: 

*By the way, anyone can claim*

**Comment by niccokunzmann** [comment]
If you try and don't succeed, please share the progress either way, so others can have a look.

**Comment by abishekvashok** [comment]
@0x48piraj any updates?

**Comment by 0x48piraj** [comment]
I have made a temp fix, okay actually I don't know! It works seamlessly and breaks uncertainly.
Please help to fix this. 
Ask for queries in the gitter channel :+1:

**Comment by niccokunzmann** [comment]
@0x48piraj Can you share a link to your branch here or create a pull request (and close it if you think so)?

**Comment by 0x48piraj** [comment]
I made many changes, I'm right now doing this!
I will make a PR as soon as I finish it, or in worst case, will just send that somewhat broken fix.

**Comment by YashKumarVerma** [comment]
@0x48piraj updates?

**Comment by 0x48piraj** [comment]
Jump into it @YashKumarVerma :+1:
