### ISSUE TITLE
Adding a custom made social section

### ISSUE THREAD

**Issue by 0x48piraj** [fossasia/labyrinth#140]
### Expected results
* Social links to connect with **_@fossasia_** and with **_labyrinth_**
* Make the UI more attractive.
* Link https://github.com/fossasia/labyrinth intelligently.
### Actual results
No social links for reaching out!

## Would you like to work on this
**Yep.**

**Comment by 0x48piraj** [comment]
Please add an `advanced` tag to this issue @niccokunzmann

**Comment by 0x48piraj** [comment]
@niccokunzmann Can you add an advanced label ?
It was a bit advanced task, and there's a GCI Task. So ..

**Comment by niccokunzmann** [comment]
@0x48piraj I add the label but you can use this also as a feature task... https://github.com/fossasia/labyrinth/blob/master/tasks/add-a-new-feature.md I think, this suits it more.

**Comment by 0x48piraj** [comment]
I have something to with that feature task :1st_place_medal:
