### ISSUE TITLE
Centralize all contributors

### ISSUE THREAD

**Issue by 0x48piraj** [fossasia/labyrinth#142]
### Expected results
All the contributors should be at one place.

### Actual results
All the contributors added their name and linked it, It breaks the game and practically sways away the attention of the player.

### Screenshots

![image](https://user-images.githubusercontent.com/5800726/34583071-3f025482-f1bc-11e7-97e0-388e8418b8a3.png)

---

![image](https://user-images.githubusercontent.com/5800726/34583099-57389caa-f1bc-11e7-9404-53d2219c01ca.png)

## Would you like to work on this

Yes!

### Approach : 

I know, they have contributed and there work should be appraised, but it should be at one place.
I'll design the `README.md` and will add all the contributors with their work.
*It will be helpful if the contributors help in this by adding their credits* :+1: :100: 

> It's not a GCI Task, just for the game!

---
What you think @niccokunzmann ?

**Comment by 0x48piraj** [comment]
@niccokunzmann Only the removing part is done.
we're going to make a separate page for contributors.
Linked issue will be this. If you're cool with it, please re-open the issue :blush:

**Comment by niccokunzmann** [comment]
#300

**Comment by niccokunzmann** [comment]
I added the new feature button to include
- [ ] github contributors
- [ ] MIT/Apache licensed libraries
- [ ] music credits (can be loaded from API)

**Comment by niccokunzmann** [comment]
@0x48piraj We have a contributors file now. I think, we can close this.
