### ISSUE TITLE
Improper rendering 

### ISSUE THREAD

**Issue by 0x48piraj** [fossasia/labyrinth#146]
### Expected results
Should be inside the cube
### Actual results
![image](https://user-images.githubusercontent.com/5800726/34587833-f729fdf4-f1cf-11e7-8ce1-ee17abacb1d7.png)

![image](https://user-images.githubusercontent.com/5800726/34587920-5f83c3b2-f1d0-11e7-9be5-a6cfa64356e0.png)

## Would you like to work on this
Yes, but can be claimed. :+1:

**Comment by duttaditya18** [comment]
Can I work on this? 😄

**Comment by 0x48piraj** [comment]
Yeah, Why not!!

**Comment by duttaditya18** [comment]
@0x48piraj Thanks! Do you want to Pair Program?

**Comment by 0x48piraj** [comment]
Yes! Why not. I will love to.

**Comment by duttaditya18** [comment]
#164 Gets ya!
