### ISSUE TITLE
Adding a Gameplay Element : Duration of Gameplay

### ISSUE THREAD

**Issue by 0x48piraj** [fossasia/labyrinth#156]
### Expected results
A timer which starts when the gamer starts playing or visits the website.

### Actual results
No such implementation exists.

## Would you like to work on this
**_Yeah!!_** *(@duttaditya18 is also pair programming with me. :100: )*

**Comment by YashKumarVerma** [comment]
#135 refers the same thing.

Duplicate perhaps.

**Comment by duttaditya18** [comment]
@0x48piraj Yup! We can work on the issue by @naveentherocker

**Comment by 0x48piraj** [comment]
Oh. I saw it now. But don't you think it's not referring to this ?
I mean it ca be but ..

> naveentherocker changed the title from **Calculate Play Time** to **Display Play Time**

**Comment by YashKumarVerma** [comment]
That name change was done about 8 hours from now, and this issue was created about an hour ago. So...

**Comment by 0x48piraj** [comment]
sweet correction : 18 hours* :wink: 
And, I wonder that you understood that issue and said mine is a dup. I'm yet not able to figure out what he wants to solve :laughing:

**Comment by YashKumarVerma** [comment]
Just pointed that out incase @naveentherocker was offline and would see his issue already merged.😂

You guys can decide yourselves. I'm in if a partner needed 😋

**Comment by naveentherocker** [comment]
Seems unfair but it's ok @0x48piraj

**Comment by duttaditya18** [comment]
@naveentherocker Thanks!

**Comment by niccokunzmann** [comment]
So, I just closed this one issue as a duplicate. I wonder if we should sync what the current status is. Who works on which part now, what are the parts that should be done to close the issue. Maybe we have different ideas impressions. I would not know since #135 does not provide and description. 

@0x48piraj @duttaditya18 @YashKumarVerma @naveentherocker Could you shortly phrase what you would like to do here?

**Comment by naveentherocker** [comment]
As @0x48piraj and @duttaditya18 have started working on this, Let them continue. I think it would be fine.

**Comment by duttaditya18** [comment]
Anyone can work on this.

Sorry that I abandoned this. I have exams upcoming. I can't really contribute at this time. Sorry.

**Comment by DNS-404** [comment]
@0x48piraj I'm currently working on some issues. After those(after 1-2 days), sure I'd like to work on this. @duttaditya18 Thank You 😃

**Comment by himanshuc3** [comment]
Hi @0x48piraj I would like to work on this issue.

**Comment by duttaditya18** [comment]
@himanshuc3 I think you can go ahead. @0x48piraj has already done some work. If you can, contact him.
