### ISSUE TITLE
Show current tile in the middle of the page

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/labyrinth#160]
### Expected results

I would like to see the tile when I move through the labyrinth.

### Actual results

Sometimes the tile where I am is hidden behind the GUI or somewhere behind the screen i.e. in 1024x800 resolution.

### Steps to reproduce the issue

Move through the whole labyrinth.
Sometimes, You can not see all the tiles.

Hints:
- You can scroll the page
- You can move the `<div id="tiles"></div>`  to the right and top depending on where you are.

**Comment by abishekvashok** [comment]
we can redesign the starting position of the player. Would that help? Or should we go for a resize?

**Comment by niccokunzmann** [comment]
I think it is ok if the tiles are as big as they are. The starting position does not influence where the player looks in this sense: It should be ok to start from any tile as it is ok to be at any tile. It should be possible to see any tile equally well. Image you have a 100x100 labyrinth. The solution should still hold. Could that clarify what I have in mind?

**Comment by niccokunzmann** [comment]
I think it is ok if the tiles are as big as they are. The starting position does not influence where the player looks in this sense: It should be ok to start from any tile as it is ok to be at any tile. It should be possible to see any tile equally well. Image you have a 100x100 labyrinth. The solution should still hold. Could that clarify what I have in mind?

**Comment by abishekvashok** [comment]
@niccokunzmann unfortunately no!

**Comment by niccokunzmann** [comment]
Can you ask me more questions?

**Comment by abishekvashok** [comment]
in case of a 100x100 labyrinth how would the player be able to manage if it is large as it is now. But that is a different issue. Are you stating to decrease the UI components here?
@niccokunzmann

**Comment by niccokunzmann** [comment]
No, I just always want to see the tile I am on. Sometimes the UI is in the way, sometimes the player walks faster that the scrolling. I think, with the GUI buttons it should be much easier to walk out of the visible area if you have a small screen.

**Comment by apappu9** [comment]
Hi, I'm new to GCI. Can I work on this?

**Comment by abishekvashok** [comment]
@apappu9 sure you can do it :)
You can ask here if you have any doubts

**Comment by apappu9** [comment]
How's this: http://rawgit.com/apappu9/labyrinth/master/index.html
- The page now scrolls to center the tile containing the player every time the player moves.
- I also moved the data cards to the side to prevent them from overlapping the tiles. I could have shifted the tiles further down instead, but since the inventory card can have an arbitrary height, I thought it would be easier to move the cards rather than moving the tiles every time inventory's height changes.

Should I make any other changes before creating a pull request?
