### ISSUE TITLE
Allow loading different levels

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/labyrinth#161]
### Expected results

As a developer, I would like to have one place to make a change, not two.

### Actual results

We have index.html and indexForest.html.
These are two labyrinths but also two pages.
To duplicate every change is unnecessary, error prone and takes long.

### Idea
To load different levels, please add a button/link for levels to load.
Loading can be done by 
1. deleting all existing tiles
2. loading the level as it is currently done at the beginning

**Comment by abishekvashok** [comment]
Can we change the logic of multiple files for levels to something like reloading the level from start but loading the next one by passing a parametered argument to `levels.js` when we reach goal?

**Comment by niccokunzmann** [comment]
Loading from a parameter should be good to have, too. This allows people to distribute a link to their changes better.

**Comment by abishekvashok** [comment]
this is easy then, can I work on it?
Note: if anyone else is interested as well, please do a comment

**Comment by 0x48piraj** [comment]
I'm in :+1: 
If anyone has a plan, spread it out! :100:

**Comment by YashKumarVerma** [comment]
In too 😄 
We all can work together if needed

**Comment by abishekvashok** [comment]
@0x48piraj @YashKumarVerma since, you all want to work on it together, we can do it, we can have a chat on it in gitter regarding it, pls see there.

**Comment by samyakbvs** [comment]
Can I also work on this?

**Comment by 0x48piraj** [comment]
Come on in !

**Comment by samyakbvs** [comment]
Have you guys done anything yet?
@0x48piraj

**Comment by 0x48piraj** [comment]
Join our gitter chat. :+1:

**Comment by samyakbvs** [comment]
Which one?

**Comment by 0x48piraj** [comment]
I already texted. 

> https://gitter.im/fossasia/labyrinth

**Comment by abishekvashok** [comment]
@0x48piraj @samyakbvs @YashKumarVerma pls see the gitter channel. We need this clear this quickly to make sure themes get added.

**Comment by arjunpandey2003** [comment]
@0x48piraj @abishekvashok @YashKumarVerma @samyakbvs since you guys are doing this issue, i would also like to contribute and will update the contribution practices.md, to add a documentation on the same, since many users have made this mistake of adding a new files. Please tell me your views on the same

**Comment by abishekvashok** [comment]
We can safely have a new issue after this is completed @arjunpandey2003

**Comment by arjunpandey2003** [comment]
@abishekvashok I am only updating contribution practices.md, since i also wanted to co-operate on this, I thought this might also be important.
Its up to you, it will be better since this issue is majorly related to the problem I mentioned.

**Comment by arjunpandey2003** [comment]
@abishekvashok I have a commit ready if you want it to go with this just tell me and I will send it to the branch you guys are working on.

**Comment by arjunpandey2003** [comment]
@niccokunzmann what do you think?

**Comment by arjunpandey2003** [comment]
@abishelvashok I also would like to contribute, if there is any un-assigned work.

**Comment by abishekvashok** [comment]
@arjunpandey2003 you are free to send the pr to the fork we r working on

**Comment by abishekvashok** [comment]
@niccokunzmann finally we have managed to do it in #339

**Comment by abishekvashok** [comment]
Can we close this now?

**Comment by 0x48piraj** [comment]
Yep. The Add different levels feature is added. I think it should be closed :+1:

**Comment by niccokunzmann** [comment]
Yes, Iwould like to check Plase guide me how to go the the next level.

**Comment by 0x48piraj** [comment]
It should load the next level once we reach the goal tile. :100: 



> I'm currently not able to play the game after some recent changes.

**Comment by niccokunzmann** [comment]
I can not reach the goal tile currently.

**Comment by 0x48piraj** [comment]
Same case with me.

> BTW, See : https://github.com/fossasia/labyrinth/pull/378

**Comment by abishekvashok** [comment]
> I can not reach the goal tile currently.

@niccokunzmann I guess the game loads the new level too quick. Shall we add a timeout?

**Comment by niccokunzmann** [comment]
I would ask the players if they would like to go to the new level. Maybe they like to eat a cake first.

**Comment by niccokunzmann** [comment]
Just an idea: If you use a dropdown menu like for the characters, you can choose levels when you are on this tile.

**Comment by niccokunzmann** [comment]
This also allows going back and forth between the levels and get items from one level to the other.

**Comment by abishekvashok** [comment]
@niccokunzmann maybe we can transporter tiles.

**Comment by niccokunzmann** [comment]
like gateways from stargate^^

**Comment by niccokunzmann** [comment]
- view/hide a level (object oriented: as a method of levels)
- add a new level object without changing the other level objects
- allow listing levels the player can go to, not forgetting their state
- have the player jump between levels and take the inventory to the next levels, too.
- ask the player to choose the level to go to

@abishekvashok @0x48piraj @arjunpandey2003 @YashKumarVerma What do you think?

**Comment by 0x48piraj** [comment]
I think, second point was already implemented by @abishekvashok 
I can work on third point. I can make a box themed popup that will allow listing of levels.
And, can use `LocalStorage()` to keep the current level data :+1: 
What do you all think ?

**Comment by abishekvashok** [comment]
@niccokunzmann seems great

**Comment by niccokunzmann** [comment]
I really want to value the time you put into this solution. At the same time, there are some things important to me. And I will comment here. I will just let air out of my inner critique and please see I do not expect you to know that before I say it:

- You use a levelCode. So, it is clear, levels need some kind of identity. Usually, we do this with names in object oriented programming. Using a levelCode with a number has two purposes: 1. identify 2. order. Mixing things up  decreases flexibility and increases dependencies and compexity.
- You put level functionality outside of level.js. How are we going to find that? If I look at level.js, I would like to know everything about the level. This is no concern for the tiles.js
- In the pr, you changed the whole levels.js file + added new functionality. While this is good intentioned, this broke the expectations of other people who were unable to cope with this and removed your code.
- calling clearGame from a tile is a violation of responsibility: There is no global state and there should not be and it should not be used.
- `$("#tiles").html("");` 
  - you kill the tiles for the level without asking it. How can you!!!!!!!! Really. Please ask the level as it should know best how to remove its tiles. I do not just remove things you created so please don't do that to the level.
  - There is `"#tiles"` This is a string constant. This belongs into a variable if it is used more often.

So, I hope you do not take this as a rejection. It is how I see architecture and order. I value the contributions and hope to initiate more understanding here so you know what I think.

**Comment by niccokunzmann** [comment]
https://vimeo.com/26330100

**Comment by abishekvashok** [comment]
@niccokunzmann I value you r suggestions :) We will try to fix the current architecture now, you are free for a revert at any time.

**Comment by niccokunzmann** [comment]
Ideas which I have which we can use but do not need to:

- rename #tiles to #levels
- levels add their tiles in divs in #levels
- the level is now added to the players and the players keeps track of all levels they can go to
- rename createTestLevel to createFirstLevel
- a player can now leave a level to go to another level
- levels can hide / show which is used when the player tells the level about entering and leaving

**Comment by niccokunzmann** [comment]
I will work on (2) now.

**Comment by abishekvashok** [comment]
I am working on it

**Comment by niccokunzmann** [comment]
@abishekvashok Please say what you are working on, so we can take part without doing work twice.

**Comment by niccokunzmann** [comment]
Done: 2, 4, 5, 6

TODO:

- [ ] let the player remember levels: call `player.addLevelFromFunction(createFirstLevel)` or `player.addLevelFromFunction(createDesertLevel)`
  - [ ] the player has a mapping and does not create levels twice
  - [ ] the player opens a dialog like with the characters to choose the level
    - [ ] `player.enterLevel(level);` is called if a level is chosen which is not the current level
  - [ ] the level gets a name as first argument
- [ ] use `player.addLevelFromFunction(createForestLevelLevel)` in the goal tile
- [ ] provide a way to the goal tile - currently, it is behind walls

**Comment by samyakbvs** [comment]
I am finding a way to the goal tile!
