### ISSUE TITLE
Remove FontAwesome : Migrate to Material Design

### ISSUE THREAD

**Issue by YashKumarVerma** [fossasia/labyrinth#177]
### Expected results
Uniform UI with similar icons / appearance

### Actual results
Font Awesome added along with material icons

### Steps to reproduce the issue
Remove font awesome / edit icons to match material design

## Would you like to work on this
`inviting members`

**Comment by niccokunzmann** [comment]
Could you add links to the usage of font awesome?

**Comment by YashKumarVerma** [comment]
![screenshot 290](https://user-images.githubusercontent.com/14032427/34638114-355bf98a-f2eb-11e7-928a-2bfc05d9cbca.png)

**Comment by YashKumarVerma** [comment]
The icons are used only for the contact / social icons

**Comment by abishekvashok** [comment]
@YashKumarVerma I would like to co-operate

**Comment by YashKumarVerma** [comment]
sure thing.
we have 2 things that need to be done
- [ ] Remove Font Awesome style link
- [ ] Replace icons and implement material icons

**Giving access to material branch on my fork**

**Comment by abishekvashok** [comment]
@YashKumarVerma sure. I would do the first one then

**Comment by YashKumarVerma** [comment]
sure

**Comment by YashKumarVerma** [comment]
@abishekvashok  create the branch if you are starting the work.

**Comment by abishekvashok** [comment]
@YashKumarVerma can you update master with upstream
`git pull upstream/master master`

**Comment by YashKumarVerma** [comment]
@abishekvashok I'd be working after a few hours, so either start work on your repo and i'll join, or 
**i given given push rights to you, you can add a new branch to mine.**

**Comment by YashKumarVerma** [comment]
***please use a different branch in cause u need to create one ***

**Comment by abishekvashok** [comment]
Ok

**Comment by YashKumarVerma** [comment]
@abishekvashok Did something ?

**Comment by abishekvashok** [comment]
No i will make a new pr now. @YashKumarVerma

**Comment by YashKumarVerma** [comment]
google's icon font doesn't have social icons. what's the cure ?

**Comment by abishekvashok** [comment]
Then we should keep fa.

**Comment by abishekvashok** [comment]
@YashKumarVerma can we close this pls?

**Comment by niccokunzmann** [comment]
There were new design issues and they are closed. Please comment to re-open this.
