### ISSUE TITLE
Merge forest level into the game

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/labyrinth#180]
### Expected results

We can play the forest level by choosing from a list of levels.

### Actual results

We have a different file and a lot of duplicated code:

- https://github.com/fossasia/labyrinth/blob/master/js/tilesForest.js
- https://github.com/fossasia/labyrinth/blob/master/js/levelsForest.js

### Hints:

To solve this issue, we can do two basic operations:

- in tilesForest.js:
  1. copy the code to the tiles.js file
  2. rename "doors:" to forest
- in levelsForest.js:
  1. copy the level over to levels.js
  2. rename the function to createForestLevel
  3. rename all "doors" tiles in the forest level to "forest"

This is a refactoring issue to improve the code quality.

After this, #161 should take care of the rest.

**Comment by abishekvashok** [comment]
Working on it.

**Comment by abishekvashok** [comment]
@niccokunzmann done in #191

**Comment by niccokunzmann** [comment]
Still needed: 

- [ ] there should be a function createForestLevel which returns the forest level.

**Comment by abishekvashok** [comment]
@niccokunzmann that will be done in the levels issue

**Comment by niccokunzmann** [comment]
This is done. We can reach it #470
