### ISSUE TITLE
No Documentation regarding How to Contribute to Tiles

### ISSUE THREAD

**Issue by naveentherocker** [fossasia/labyrinth#19]
No Any Documentation regarding how to contribute to Tiles. So a newcomer will definitely face many problems while Contributing.

**Comment by niccokunzmann** [comment]
@naveentherocker Thanks for the PR. In order to close this issue, I would also suggest:
- [ ] describe which javascript files to edit and how
- [ ] add a tile and describe every step which is needed

**Comment by 0x48piraj** [comment]
@niccokunzmann
I can help in describing which files to edit, but can you help me on the **how**

Is it that, I have to describe git commands on how to clone this repo and edit the files or something else ??

**Comment by niccokunzmann** [comment]
@0x48piraj Git commands are also helpful, especially for the workflow of fork -> clone -> branch -> push -> pull-request

When editing files, I can help to describe which files:
1. The tile file needs to be added to the https://github.com/fossasia/labyrinth/tree/master/tiles/ directory.
2. Add a new type of tile in the tiles.js file. Best as a copy of an existing tile which describes the behavior. e.g. https://github.com/fossasia/labyrinth/blob/a2cc000cfecdd4e29870ff6075b5703ef28c01e3/js/tiles.js#L159
3. Add the tile to [levels.js](https://github.com/fossasia/labyrinth/blob/a2cc000cfecdd4e29870ff6075b5703ef28c01e3/js/levels.js)

But I guess, a tutorial with an example would be even better.

**Comment by abishekvashok** [comment]
@niccokunzmann #53 as @naveentherocker was'nt working on it.
