### ISSUE TITLE
Social Buttons Not properly aligned

### ISSUE THREAD

**Issue by YashKumarVerma** [fossasia/labyrinth#205]
### Expected results
Icons must appear at center of element

### Actual results
![image](https://user-images.githubusercontent.com/14032427/34642361-b961e0fe-f337-11e7-9dcf-3fbe2a653337.png)

### Steps to reproduce the issue
Fix the styling

## Would you like to work on this
Anyone can claim

**Comment by duttaditya18** [comment]
@YashKumarVerma On it!

**Comment by niccokunzmann** [comment]
@YashKumarVerma Please see if we can close this.
