### ISSUE TITLE
Format Entire Codebase

### ISSUE THREAD

**Issue by YashKumarVerma** [fossasia/labyrinth#208]
### Expected results
A well-formatted codebase

### Actual results
Files are ill-structured and difficult to comprehend.

### Steps to reproduce the issue
- format the entire codebase
  - [x] gui.js
  - [x] inventory.js
  - [ ] level.js- claimed 
  - [x] levels.js
  - [x] player.js
  - [x] tiles.js

## Would you like to work on this
All Should. Time to time needed.

**Comment by saarthakchats** [comment]
@YashKumarVerma 
Can I do level.js, formatting?

**Comment by YashKumarVerma** [comment]
Sure

**Comment by niccokunzmann** [comment]
@YashKumarVerma @saarthakchats There is three days no progress. I would like to keep the issue tracker small. I will close this now. You can open a new issue. Also, travis now helps us find out where we have to change what.

**Comment by YashKumarVerma** [comment]
@niccokunzmann Sure 
as when @saarthakchats asked if he could do the same, i didn't go ahead with mine. Hope that he'd open a new issue for the same.
