### ISSUE TITLE
Close Alert box automatically on movement to new tile.

### ISSUE THREAD

**Issue by duttaditya18** [fossasia/labyrinth#229]
### Expected results
It closes automatically.

### Actual results
It does not and remains open.

### Steps to reproduce the issue
Just visit a tile with an alert box and try pressing an arrow key.

### Would you like to work on this
Yup!

Update from @niccokunzmann : 
>To make this an advanced issue, please implement the following API which abstracts the calls to swal such as
```
swal({
                type: 'info',
                title: 'Hi there',
                text: "I'm a nameless monster, welcome to my forest. You may find something interesting or equally horrific, let's rely on your fate.",
});
```
>* [ ] Add the following function to the PlacedTile: alertInfo(title, text)
>* [ ] close the alert automatically when the player leaves the tile
>* [ ] have all tile calls replaced by this API

**Comment by niccokunzmann** [comment]
To make this an advanced issue, please implement the following API which abstracts the calls to swal such as

```
swal({
                type: 'info',
                title: 'Hi there',
                text: "I'm a nameless monster, welcome to my forest. You may find something interesting or equally horrific, let's rely on your fate.",
});
```

- [ ] Add the following function to the PlacedTile: `alertInfo(title, text)`
- [ ] close the alert automatically when the player leaves the tile
- [ ] have all tile calls replaced by this API

**Comment by duttaditya18** [comment]
@niccokunzmann All right. I will make a new PR solving this new thing. Can you check out my existing PR? Thanks!

**Comment by duttaditya18** [comment]
I am working on it!

**Comment by duttaditya18** [comment]
@niccokunzmann Open this again! I am working on this.

**Comment by niccokunzmann** [comment]
Thanks, in my eyes, this closes the issue. Also thanks for adding the documentation.

**Comment by niccokunzmann** [comment]
Great!

**Comment by niccokunzmann** [comment]
I mean: It is not 100% as I intended it but I think it is better than I intended it. I would have made the alrts part of the player but that is not where they belong.
