### ISSUE TITLE
Can walk through wall

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/labyrinth#233]
### Expected results

I would like to stop at the wall

### Actual results

I can walk through the wall: right-right-up

### Steps to reproduce the issue

http://rawgit.com/fossasia/labyrinth/master/index.html walk:
right-right-up

**Comment by STEdirisuriya** [comment]
Sorry for disturbing, I add this bug already on my issue, https://github.com/fossasia/labyrinth/issues/206

**Comment by duttaditya18** [comment]
@niccokunzmann On it!

**Comment by STEdirisuriya** [comment]
@duttaditya18 please tag #206 too in your PR
