### ISSUE TITLE
Index.html needs more social links

### ISSUE THREAD

**Issue by saarthakchats** [fossasia/labyrinth#251]
### Expected results
All social links
### Actual results
Missing some
### Steps to reproduce the issue
Add them
## Would you like to work on this
Yes

**Comment by niccokunzmann** [comment]
Which social links are missing in your view? This should be described otherwise there is no clear closing criterion and I do not know when to close this.

**Comment by harsh-jindal** [comment]
@saarthakchats I would like to work on this. Can you specify which social links?

**Comment by niccokunzmann** [comment]
@harsh-jindal You can add social links if you like. You can also open another issue for that. We have 6 days no response, so I close this.
