### ISSUE TITLE
Add a new task

### ISSUE THREAD

**Issue by arjunpandey2003** [fossasia/labyrinth#257]
### Expected results
New task added
### Steps to reproduce the issue
Create new file in tasks dir
## Would you like to work on this
Open for everyone.

**Comment by saarthakchats** [comment]
Adding another task... Working on it!

**Comment by samyakbvs** [comment]
I have also added a task #258

**Comment by niccokunzmann** [comment]
New tasks we added, closing this. Please comment to re-open.
