### ISSUE TITLE
Yellow tile does not fit in the labyrinth

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/labyrinth#261]
### Expected results

I would like to enter the yellow tile #260 and see a yellow wall and yellow ground

### Actual results

I see a yellow square and no ground

### Steps to reproduce the issue

http://rawgit.com/fossasia/labyrinth/master/index.html
go right right down down

**Comment by duttaditya18** [comment]
@niccokunzmann This is the problem. People just want to solve Google Code In tasks and they add these tiles in improper dimensions and stuff. The tile had 0 work put into it.

I don't think that the person who put it, even had opened a Vector Graphics Editor for making this tile. This is seriously pathetic.

**Comment by niccokunzmann** [comment]
So, you would like to be sure that the quality of the work fullfills standarts. 
So, since I do not make value judgements, https://rfc.zeromq.org/spec:42/C4/ I would ask you to create a pull request which reverts these changes. Is that possible? You can argue why removing this makes it better and I am sure, we can merge it, too.

**Comment by duttaditya18** [comment]
@niccokunzmann What is the point of that now. The person who had made the PR must have got his task accepted in GCI. I will just make this yellow tile the correct dimensions and make a PR.

**Comment by niccokunzmann** [comment]
No. The task it not accepted, should not be. The task should state that all issues created from this one are closed.

**Comment by duttaditya18** [comment]
@niccokunzmann All right. On it!

**Comment by niccokunzmann** [comment]
Thanks @Beta-King for resolving this!

**Comment by duttaditya18** [comment]
@Beta-King Awesome!

**Comment by Beta-King** [comment]
Thank :D

**Comment by niccokunzmann** [comment]
@duttaditya18 There is something in accepting imperfect work: This collaboration is not about the work, it is about the people. If I mere 1. I can always revert. 2. I value the work of the person and it is much more fun for this person to contribute again.
As a maintainer, I think and hope, if I reject a pull request, there MUST be a written down rule and a justification for that rule.

**Comment by niccokunzmann** [comment]
https://www.youtube.com/watch?v=uj-li0LO_2g

**Comment by Beta-King** [comment]
I had made an error in the previous PR i guess cause i was using Sketch instead of Inkscape; i realised the error and so made the necessary changes ASAP :D

**Comment by niccokunzmann** [comment]
Thanks, I will close this now.
