### ISSUE TITLE
How to add a character 

### ISSUE THREAD

**Issue by samyakbvs** [fossasia/labyrinth#277]
In the how to add character section it isn't mentioned that the character shouldn't be an image of a renowned personality and if you want to add then you should have a proof that you are allowed to use his/her image
Also for GCI students the character should be your own work it can't be an image copied from somewhere

Working on it!!

**Comment by STEdirisuriya** [comment]
Oh good, CAn you add there "Don't use white spaces in characters,"

**Comment by dhruvkumarverma** [comment]
Add the same to #244 . ask @YashKumarVerma  to update the docs issue. Let's have only one centralized docs issue. Different issues make it difficult to manage often

**Comment by niccokunzmann** [comment]
It is the same with music: rights are everywhere. I added some hints in the contributing.md: https://github.com/fossasia/labyrinth/blob/master/CONTRIBUTING.md -> licensing.

**Comment by samyakbvs** [comment]
Okay will fix it till evening

**Comment by samyakbvs** [comment]
Hey you mean to say that I should create a new HTML file in which there is all information on the copyright issues?
