### ISSUE TITLE
Need to add documentation of how to add Music/Sounds

### ISSUE THREAD

**Issue by saarthakchats** [fossasia/labyrinth#282]
#245 

Working on it

**Comment by duttaditya18** [comment]
@saarthakchats Add documentation on how to make sound effects in Audacity or any other open source sound editor as well.

**Comment by dhruvkumarverma** [comment]
please add the same to #244

**Comment by YashKumarVerma** [comment]
Kindly add the documentation to the documentation folder.

**Comment by niccokunzmann** [comment]
Documentation is added. https://github.com/fossasia/labyrinth#how-to-add-music
