### ISSUE TITLE
solve license clash for the files in the /audio folder

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/labyrinth#292]
### Expected results

I would like to know the license of the files 
- /audio/minecraft.mp3
- /audio/outdoor.mp3

### Actual results

No licensing details are provided. I doubt they are AGPL.

Solution Ideas:
- either add the license
- or remove the files

Hints:
Please use git blame to find the person who added the file and ask for the license to be provided.

**Comment by saarthakchats** [comment]
@niccokunzmann 
I have also added some sound in my PR #280 
I will add licensing right after that PR is merged. Pls, merge that so that I can immediately work on the next one.

**Comment by saarthakchats** [comment]
I have added License now
https://github.com/fossasia/labyrinth/pull/280

**Comment by saarthakchats** [comment]
Pls merge

**Comment by duttaditya18** [comment]
I think this is solved now.

**Comment by niccokunzmann** [comment]
Thanks! This is solved.
