### ISSUE TITLE
Add more alerts

### ISSUE THREAD

**Issue by saarthakchats** [fossasia/labyrinth#298]
### Expected results
Good and meaningful alerts kind of giving hints.
### Actual results
Very few alerts which aren't meaningful
### Steps to reproduce the issue
Add them.
## Would you like to work on this
Yes, I will enable this task as well in tasks folder. Please don't work on it without my consent.

# Note:-
Alerts should also be related to the theme, when new levels are added.

**Comment by niccokunzmann** [comment]
I think, there was a pull request for that. We can link it here.

**Comment by duttaditya18** [comment]
Close this.

**Comment by niccokunzmann** [comment]
Three days no update, closing this. We can re-open it later, just comment.
