### ISSUE TITLE
Add style checker

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/labyrinth#3]
Adding a style checker to check code  To keep the game easy to contribute in the future improving the code quality will be great, enabling a PR style checker like coala in Travis CI would be great.
Can we have something like that?

**Comment by abishekvashok** [comment]
@meets2tarun @niccokunzmann @xeon-zolt pls check #4

**Comment by xeon-zolt** [comment]
https://travis-ci.org/fossasia/labyrinth/builds/314359991#L1372

**Comment by abishekvashok** [comment]
That's because lint tests are failing as code is not properly lint @xeon-zolt the checker is working fine :)
