### ISSUE TITLE
Add Automatic Code Quality check

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/labyrinth#30]
Some code metrics require code to be added, some code metrics want to remove the same code. [Source](https://github.com/fossasia/labyrinth/pull/29/files#diff-eacf331f0ffc35d4b482f1d15a887d3bL7).
Please add a code metric which runs automatically to this repository.

You can help by describing which one to use and how to add it.

**Comment by sayak119** [comment]
@niccokunzmann can we add codacy ?

**Comment by niccokunzmann** [comment]
Yes, please :)

**Comment by sayak119** [comment]
**Steps - **
1. Login with GitHub.
2. Go to organizations present in upper right hand corner drop down.
3. Create new organization.
4. Open the new organization you just created.
5. Go to plan and billing and select open source. Fill a form that appears after this step.
6. Go to Teams and select Developer and then add project. same with Administrator.
7. When the project is evaluated for the first time Go to settings present in left bottom, then to Integrations. 
8. GitHub will already be selected (if not then Click on Add Integration).
9. Tick all the check-boxes.
From next PR's codacy will start to evaluate the code. Coverage can also be added.

**Comment by niccokunzmann** [comment]
I added codacy. Thanks for the hints!
