### ISSUE TITLE
Walk through wall

### ISSUE THREAD

**Issue by samyakbvs** [fossasia/labyrinth#303]
In the yellow tile, player is able to walk through the wall
Working on it!

**Comment by brain-sick** [comment]
i hope, you have solved it as it issue in the yellow tile is looking fixed

**Comment by niccokunzmann** [comment]
@samyakbvs Please check and close this, then.

**Comment by brain-sick** [comment]
not the yellow tile , but in few other location i noticed this problem, let me solve this

**Comment by samyakbvs** [comment]
@brain-sick You can open other issues for other tiles
