### ISSUE TITLE
Badges

### ISSUE THREAD

**Issue by Ploypiti** [fossasia/labyrinth#307]
### Expected results
Enable badge achievement when players reach a certain tile, e.g., discovered a treasure.
![image](https://user-images.githubusercontent.com/32614202/34706604-58ef2550-f53b-11e7-8c03-aa3fa8789c5d.png)
_Source: http://en.wikipedia.org/wiki/Bartle_Test_
### Steps to reproduce the issue
Design & Define the badges.
## Would you like to work on this
Yep

**Comment by STEdirisuriya** [comment]
Good Job!

**Comment by STEdirisuriya** [comment]
Can we support for making Badges.

**Comment by Ploypiti** [comment]
@STEdirisuriya Yeah, sure. I'm adding the doc.
