### ISSUE TITLE
add license files

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/labyrinth#310]
### Expected results

https://github.com/fossasia/labyrinth/pull/296#issuecomment-356235659 The files in this pull reques must have a license close by.

### Actual results

The files do not have a license in them.

**Comment by saarthakchats** [comment]
Working on it @niccokunzmann

**Comment by niccokunzmann** [comment]
Seems solved. I can not find them there any more. If anyone could add the pull request here, much appreciated.
