### ISSUE TITLE
Add Contributors Section to the Site

### ISSUE THREAD

**Issue by naveentherocker** [fossasia/labyrinth#318]
### Expected results
List of Contributors who contributed to the Game along with their no.of Contributions
### Actual results
No Information regarding Contributors
## Would you like to work on this
Yes I am working on it

**Comment by niccokunzmann** [comment]
@naveentherocker There is issue #142 could you synchronize with this? Is this one different?

**Comment by naveentherocker** [comment]
@niccokunzmann #142 is Slightly different from this
