### ISSUE TITLE
Add a goal tile

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/labyrinth#32]
Please add a tile which is different from the other tiles.
This tile is the goal tile.

1. Add a tile to the [rooms](https://github.com/fossasia/labyrinth/tree/master/tiles/rooms) as tiles/rooms/floor/goal.svg derived from tiles/rooms/floor/caro.svg which is recognizable as a goal
2. In the tiles.js file, the implementation should look something like this, if you can enter the room from all sides:
   ```
   goal: Object.assign({}, OpenDoors, {
    createImages: function() {
      this.wallTop = this.createImage("tiles/rooms/wall/top.svg");
      this.wallRight = this.createImage("tiles/rooms/door/right.svg");
      this.ground = this.createImage("tiles/rooms/floor/goal.svg");
    },
    visit: function() {
      // add a alert here that the person reached the goal
    }
   }
    ```
3. In the [levels](https://github.com/fossasia/labyrinth/blob/master/js/levels.js) folder, please add the goal tile.

If you have questions, please ask below. #19 Could be a second issue that would be solvable by describing the things you do here.

**Comment by abishekvashok** [comment]
Shouldn't the goal tile be visible?

**Comment by niccokunzmann** [comment]
You can make it visible once the game starts, sure...

**Comment by abishekvashok** [comment]
Suggested approach, the goal tile can be entered from any direction. But the doors will be opened if the tile before the goal tile permits it so, an implementation will be done player.js file which will determine if the goal tile is reached or not. But, what to do after reaching a tile, should we go for a new level, if so how?

**Comment by niccokunzmann** [comment]
Hm. I think, an alert would be good just to let other people have a discussion and try it out. In the future, we can create another level but for that we should first have the tile.

I assume an implementation you have in mind but I do not know... You do not need to modify the player.js file because the player tells the tile when he enters, looks at it, ...
Whenever you do something like `if (object.tile==XY) { doZ() }` You can use the object dispatch `object.doZ()` where the doZ is empty for all other objects. But this allows object-oriented flexibility to introduce other objects which can doZ and decreases the size of objects, and as such allowing a better separation of concerns, reducing the risk, that you get [a god class](https://en.wikipedia.org/wiki/God_object).

**Comment by abishekvashok** [comment]
@niccokunzmann I am struggling designing the tile, my designs end up being ugly. I don't know if I could inkscape as I do photoshop. :(

**Comment by niccokunzmann** [comment]
At the end it needs to be an image, svg is best. If you can design it with photoshop, you can do it. Maybe you want to include png, too. That is ok for me, too.

**Comment by abishekvashok** [comment]
I will get some designs early tomorrow.

**Comment by abishekvashok** [comment]
![image](https://user-images.githubusercontent.com/8947010/34348848-7bd920b0-ea33-11e7-87a6-873032263f65.png)

**Comment by niccokunzmann** [comment]
Wow. wonderful :)

**Comment by abishekvashok** [comment]
Adding it

**Comment by abishekvashok** [comment]
@niccokunzmann done in #51
