### ISSUE TITLE
walk though walls

### ISSUE THREAD

**Issue by brain-sick** [fossasia/labyrinth#334]
### modify code

##Yes

**Comment by STEdirisuriya** [comment]
https://github.com/fossasia/labyrinth/issues/206 11th point. Don't make issues for same things, Work on it from that issue.

**Comment by STEdirisuriya** [comment]
If you want to work no problem work on issue that's already created.

**Comment by niccokunzmann** [comment]
This issue is not reproducible, I can not know when to close this as this can always happen. Closing this and hoping the other issues cover that.
