### ISSUE TITLE
Document how to play the game

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/labyrinth#34]
You need the arrow keys, up down right left to move in the labyrinth.
But no-one knows!
Please add it somewhere

- When the game starts (most important)
- In the README

**Comment by YashKumarVerma** [comment]
working on it

**Comment by YashKumarVerma** [comment]
How's this 
---
# How to play the awesome game ?
- [Open the game *click here*](http://rawgit.com/fossasia/labyrinth/master/index.html) 
- You'll see the base room with doors on it's walls. Notice the `red and grey` tile.
- Notice that there are 3 doors/openings on 3 walls.

![http://lsppublicschool.org/yashkumarverma-host/vault/1.JPG](http://lsppublicschool.org/yashkumarverma-host/vault/1.JPG)

- Now press the `upward arrow` button to create a room above the current room. (precisely, top left corner of your screen or north-west direction taking north towards the top of your screen)
![http://lsppublicschool.org/yashkumarverma-host/vault/2.JPG](http://lsppublicschool.org/yashkumarverma-host/vault/2.JPG)
- Now you can see a new block/room added. Also see that the color difference of the tiles. The bring red shows the current (red) active tile and the dark (black) tile shows the rest of tiles. Let's move a bit towards right now.`press right arrow`
![http://lsppublicschool.org/yashkumarverma-host/vault/3.JPG](http://lsppublicschool.org/yashkumarverma-host/vault/3.JPG)
- Now we can see the tiles to the right (top-right precisely). We can see the doors towards all sides/walls of the room/block. so let's move more in the game. 
![http://lsppublicschool.org/yashkumarverma-host/vault/4.JPG](http://lsppublicschool.org/yashkumarverma-host/vault/4.JPG)
- Now we can see that there's no tile towards the top, so now we cannot move more in that direction. Let's go about making a complete grid.

- Do you see a  way now too ? There is still an open door to explore !
![http://lsppublicschool.org/yashkumarverma-host/vault/5.JPG](http://lsppublicschool.org/yashkumarverma-host/vault/5.JPG)
- let's build that too !
- All Done
![http://lsppublicschool.org/yashkumarverma-host/vault/6.JPG](http://lsppublicschool.org/yashkumarverma-host/vault/6.JPG)

**Comment by niccokunzmann** [comment]
@YashKumarVerma Cool, we should use that. Where would you like to add this? Would you like to add this as a separate html file which we can link to? e.g. with a "?" at the corner of the page?

**Comment by YashKumarVerma** [comment]
sure i can add the same as html too. This was only to ensure that it was suitable for the project.

So now as it appears that the content is fine, i can deploy it too 😄
