### ISSUE TITLE
Add licenses for sound #

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/labyrinth#346]
### Expected results

All sound files are licensed.

### Actual results

Some were added in #280 without license

### Steps to reproduce the issue

see #280 and the /audio folder

https://github.com/fossasia/labyrinth/pull/280#issuecomment-356363778 - please check here for the files and advice.

**Comment by saarthakchats** [comment]
@niccokunzmann I will be adding some licenses.

**Comment by samyakbvs** [comment]
Me too
