### ISSUE TITLE
Remove compressed files from travis code check

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/labyrinth#372]
### Expected results

A code quality check which tells us where to fix problems

### Actual results

The code quality check outputs huge files. 

### Steps to reproduce the issue

https://travis-ci.org/fossasia/labyrinth/builds/327227735

Ideas for a solution:
- look in the js and css folder for included external code like jquery or materialize or sweetalert
- ignore this code in coala

**Comment by YashKumarVerma** [comment]
attempting
