### ISSUE TITLE
Game not starting

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/labyrinth#379]
### Expected results

It should work.

### Actual results

It is not working.

### Steps to reproduce the issue

Go to the website.

## Issues

SyntaxError: missing ) after argument list
[Learn More]
tiles.js:834:1
unreachable code after return statement
[Learn More]
levels.js:24:2
SyntaxError: missing } after function body
[Learn More]
levels.js:58
note: { opened at line 12, column 0
levels.js:12
SyntaxError: missing } after property list
[Learn More]
gui.js:31:6
note: { opened at line 25, column 12

**Comment by abishekvashok** [comment]
Since these are simple typos I am going to wait approx 30 mins, if no one is claiming I will do this.

**Comment by samyakbvs** [comment]
Claming

**Comment by abishekvashok** [comment]
@samyakbvs ok sure go on.

**Comment by samyakbvs** [comment]
I will only be able to do them when @niccokunzmann merges my current PR https://github.com/fossasia/labyrinth/pull/377

**Comment by abishekvashok** [comment]
@samyakbvs make a new branch on your fork tracking upstream master and work there
`git cehckout jacktherover --track upstream master`

**Comment by samyakbvs** [comment]
I including the changes in the same PR

**Comment by samyakbvs** [comment]
So no problem

**Comment by samyakbvs** [comment]
unreachable code after return statement
[Learn More]
levels.js:24:2

@abishekvashok What do I have to do in this?

**Comment by samyakbvs** [comment]
Oh I got it

**Comment by abishekvashok** [comment]
@samyakbvs sorry to be late : )Happy since you got it
