### ISSUE TITLE
Activate github pages

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/labyrinth#38]
Please activate Github pages from the master branch. Then, we can play the game from https://fossasia.github.io/labyrinth

**Comment by YashKumarVerma** [comment]
shall i work on it @mariobehling

**Comment by niccokunzmann** [comment]
@YashKumarVerma If you have Admin rights, you can do that.

**Comment by YashKumarVerma** [comment]
@niccokunzmann  I don't. So i can't 😢

**Comment by Beta-King** [comment]
Is someone working on this then ?? ;D

**Comment by YashKumarVerma** [comment]
@Beta-King only admins can create new branches i guess.

**Comment by niccokunzmann** [comment]
I think, we do well without it. Maybe we will activate it in the future. You can comment, re-open or create a new issue about this if you think this is really necessary.
