### ISSUE TITLE
UI too large

### ISSUE THREAD

**Issue by YashKumarVerma** [fossasia/labyrinth#386]
### Expected results
A UI that fits a screen (`1366x768:my config`)

### Actual results
![screenshot 293](https://user-images.githubusercontent.com/14032427/34803850-88f4c370-f69b-11e7-88aa-bb0e15df07d0.png)

### Steps to reproduce the issue
- Fix Stylesheets

## Would you like to work on this
No

**Comment by niccokunzmann** [comment]
A hint: In firefox and other browsers, there are developer tools, where you can change the resolution of the browser.

**Comment by duttaditya18** [comment]
We have updated the sidebar to be more suitable for all screen sizes.

**Comment by niccokunzmann** [comment]
Yes, I think the UI is smaller now. The stated resolution works.
