### ISSUE TITLE
Contributers page broken

### ISSUE THREAD

**Issue by YashKumarVerma** [fossasia/labyrinth#387]
### Actual results
![screenshot 294](https://user-images.githubusercontent.com/14032427/34803906-da43de3c-f69b-11e7-81d7-b65f24187821.png)

### Steps to reproduce the issue
-Link scripts

## Would you like to work on this
No

**Comment by niccokunzmann** [comment]
looks like jquery is not loaded.

**Comment by duttaditya18** [comment]
Sure. I'll work on this.

**Comment by niccokunzmann** [comment]
I edited the current page in #411

**Comment by niccokunzmann** [comment]
It is loading again.
