### ISSUE TITLE
add a promotional video

### ISSUE THREAD

**Issue by STEdirisuriya** [fossasia/labyrinth#394]
### Expected results
add promo video about labyrinth

### Actual results
still no

### Steps to reproduce the issue
use open source editor

## Would you like to work on this
Yes of course

**Comment by niccokunzmann** [comment]
#391 A promotional video was added.

I think, issues should be solvable by everyone. So, closing this.

**Comment by niccokunzmann** [comment]
https://gitter.im/fossasia/labyrinth?at=5a5732fa61a861c927fd3edc
