### ISSUE TITLE
Add version updated on readme.md

### ISSUE THREAD

**Issue by STEdirisuriya** [fossasia/labyrinth#395]
### Expected results
Add versions and details on readme.md

### Actual results
not yet

### Steps to reproduce the issue
update readme.md

## Would you like to work on this
I'll do, @niccokunzmann and others I want help,

**Comment by STEdirisuriya** [comment]
@niccokunzmann Please send me updates in earlier

**Comment by niccokunzmann** [comment]
So, I can not help as I want to know more: which version do you want to update? What does versioning have to do with the README file?

**Comment by duttaditya18** [comment]
@niccokunzmann I think we can add a version id on the website. Like there in fossasia/open-event-webapp

**Comment by niccokunzmann** [comment]
I my eyes, we do not have a version. We have an almost always working product which is alive.
http://hintjens.com/blog:85 - this inspires me.
What do you think about the article?

**Comment by duttaditya18** [comment]
@niccokunzmann the "version id" is just the commit sha. i think we can do that.

**Comment by niccokunzmann** [comment]
:) ahh. ok. Cool, I like that, too! I wonder how you will do that. I
have no clue. Maybe you will surprise me with it.

**Comment by duttaditya18** [comment]
@niccokunzmann Can this issue be considered a "new feature"?
