### ISSUE TITLE
Show music tile license when playing it

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/labyrinth#398]
### Expected results

We have music whose rights owner want us to show a certain license when the music is played.
The music is played, when we enter a tile.

### Actual results

We do not display tile music license information.

### Hints

Please have a look at the background music and use the same structure to create a structure for the tile music:

```
tileMusic = {
  "audio-name" : {
    // same is in background music
   }
}
```

Then, change the tile music call to use `tileMusic` to play it.
Add the credits below the currently shown background music credits.
When the player leaves a tile, delete all tile music credits.

**Comment by duttaditya18** [comment]
Will work on it!

I love making these APIs.

**Comment by niccokunzmann** [comment]
@duttaditya18 Please have a look at this: http://creativecommons.org/choose/  At the bottom, it creates HTML code. I think for the best flexibility, we should use HTML as license text an not split it up. What do you think?

**Comment by duttaditya18** [comment]
@niccokunzmann Awesome idea! Will do that.
