### ISSUE TITLE
Tiles not aligned in Labyrinth properly

### ISSUE THREAD

**Issue by Beta-King** [fossasia/labyrinth#423]
### Expected results
aligned tiles

### Actual results
not aligned tiles (dis-figured and size not supported)

### Steps to reproduce the issue
play labyrinth
find tiles (river and boat)

## Would you like to work on this
YES!!

**Comment by niccokunzmann** [comment]
@Beta-King By now, you should have found tiles. Please give updates. This can be closed soon, if no updates arrive.
