### ISSUE TITLE
Create pixbay folder and license

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/labyrinth#424]
### Expected results

There are tiles which use content which is under CC0.
I expect to see
- a folder for these tiles
- a LICENSE in the folder which is from pixbay
- a README which states when to add tiles there.

### Actual results

Nothing like this but
- merged #419 
- pull request #420

**Comment by kubami9** [comment]
I'd like to work on it :)

**Comment by niccokunzmann** [comment]
Sure, please go ahead.

**Comment by niccokunzmann** [comment]
I will close if all images are in this folder which belong there, see the two pull requests

**Comment by niccokunzmann** [comment]
https://github.com/fossasia/labyrinth/tree/master/tiles/CC0%20license%20tiles

**Comment by saarthakchats** [comment]
@niccokunzmann 
Doing it
