### ISSUE TITLE
Game broken.

### ISSUE THREAD

**Issue by YashKumarVerma** [fossasia/labyrinth#43]
The current deployment is not working. 
![image](https://user-images.githubusercontent.com/14032427/34430440-3777f55e-ec8b-11e7-8ba8-163c26a3b936.png)

**Comment by STEdirisuriya** [comment]
See this - https://github.com/fossasia/labyrinth/issues/42
I said it. Please close this!

**Comment by niccokunzmann** [comment]
Thanks for reporting! Let's discuss this in #42.
