### ISSUE TITLE
Add Tasks to the GCI

### ISSUE THREAD

**Issue by naveentherocker** [fossasia/labyrinth#438]
### Expected results
Every Tasks in the `Tasks` in GCI
### Actual results
There are few tasks which are not added
### Tasks which are not added

- https://github.com/fossasia/labyrinth/blob/master/tasks/Clues.md
- https://github.com/fossasia/labyrinth/blob/master/tasks/Create-A-wall.md
- https://github.com/fossasia/labyrinth/blob/master/tasks/enhancement.md

**Comment by abishekvashok** [comment]
@naveentherocker pls note that this is at the discrimination of the organization admin, mentors post tasks and admin has to approve them. I belive these are posted but unfortunately not accepted yet. Please wait.
Let's close this issue as we can't do anything much on this.

**Comment by niccokunzmann** [comment]
Thanks for updating. Clues will not be added as we agreed it is too easy. I will look at the two other tasks.

**Comment by niccokunzmann** [comment]
We can close this, I will add no more tasks. Please comment if you like to re-open it.
