### ISSUE TITLE
Add tiles.

### ISSUE THREAD

**Issue by STEdirisuriya** [fossasia/labyrinth#44]
I try to add more floors. And also walls and doors.

**Comment by abishekvashok** [comment]
Please close this as it was solved

**Comment by STEdirisuriya** [comment]
no I trying to add more.

**Comment by STEdirisuriya** [comment]
#Don't close this I am trying to add more

**Comment by abishekvashok** [comment]
Sure

**Comment by niccokunzmann** [comment]
@STEdirisuriya If we can help you in any way, please let us know..

**Comment by STEdirisuriya** [comment]
@niccokunzmann add tutorials showing how to add tiles, walls,,,.......................

**Comment by niccokunzmann** [comment]
Documentation is as important as code. Yes, it is useful and we have people write documentation as it speeds up the contributions.

**Comment by abishekvashok** [comment]
@STEdirisuriya you have one in README.MD. Fire up a new issue if you feel we can improve it much more.

**Comment by niccokunzmann** [comment]
I see more tiles are added. I am closing this. Please open a new issue if you need it. I want to keep the issue tracker small.
