### ISSUE TITLE
Add music to tiles 

### ISSUE THREAD

**Issue by Beta-King** [fossasia/labyrinth#444]
### Expected results
Added music to tiles

### Actual results
no music to tiles

### Steps to reproduce the issue
play labyrinth

## Would you like to work on this
YES !!

**Comment by abishekvashok** [comment]
@Beta-King pls close this. You don't need issues to add music, just do a straight forward PR to add characters, music, background etc. You will need issues to suggest ui enhancements and any change in the code except the above mentioned ones

**Comment by Beta-King** [comment]
Yeah but during the PR someone told me to open an issue so i did but yeah i agree with you :D
