### ISSUE TITLE
Add save game feature

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/labyrinth#446]
### Expected results

Player should be able to save their game state and reload it in the next visit.

### Actual results

No such feature

### Steps to reproduce the issue

Go to the game and play it

## Would you like to work on this

yes, taking it up as part of gci

**Comment by abishekvashok** [comment]
Proposed solution,
Save entire #tile div into the local storage along with inventory items.
On visit,
check for save, if save present, load the #tile div back into the game, items one by one into inventory.

**Comment by niccokunzmann** [comment]
We have a structure like this:
```
player -> level -> tiles
       -> badges
       -> inventory -> items
```
I think, it is ok if we start from any position after loading the game state and discovering again. Like in other games, you like to have your inventory but you do not expect the game to look the same as it evolves all the time. So, you want to take the most important parts with you.

I think:
Adding a `saveState() -> state` and `loadState(state)` in the player and inventory could be a start. `state` is JSON serializable.

**Comment by abishekvashok** [comment]
@niccokunzmann working on it.

**Comment by abishekvashok** [comment]
@niccokunzmann should we add the functions to the player class or in a seperate js file as global functions?

**Comment by niccokunzmann** [comment]
Saving and storing should be in a different file as it does not have to do with anything existing. Extracting the state from the player is responsibility of the player.

**Comment by abishekvashok** [comment]
@niccokunzmann finally done in #472
