### ISSUE TITLE
Game is broken

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/labyrinth#454]
### Expected results

it should work

### Actual results

It's not working

### Log

TypeError: tileSpecification is undefined
level.js:32:7

### Steps to reproduce the issue

Go to the game website: http://rawgit.com/fossasia/labyrinth/master/index.html

## Would you like to work on this

Waiting for somebody to take it, if it is not taken up in the next 1 hour, I will work on it :)

**Comment by STEdirisuriya** [comment]
I think reason for this came again and again is while we pushed after cloned some errors with there browsers are came to this, I can remember when I cloned repo and see it nothing displayed game is broken, but on the main repo displayed game corretly, No commits ahead or behind, I don't know why. After we changed and push the error came to game, This error have only to several OS or several browsers or both. @niccokunzmann

**Comment by abishekvashok** [comment]
> I think reason for this came again and again is while we pushed after cloned some errors with there browsers are came to this, I can remember when I cloned repo and see it nothing displayed game is broken, but on the main repo displayed game corretly, No commits ahead or behind, I don't know why. After we changed and push the error came to game, This error have only to several OS or several browsers or both. @niccokunzmann

The game uses js code that all browsers (main ones) I am aware of support out of the box.

**Comment by niccokunzmann** [comment]
This happens if someone adds a tile which is undefined

**Comment by niccokunzmann** [comment]
So, there is a tile in the current level which is not correctly referenced.

**Comment by niccokunzmann** [comment]
`TypeError: tileSpecification is undefined[Learn More]`

**Comment by abishekvashok** [comment]
Let me find that tile

**Comment by abishekvashok** [comment]
@niccokunzmann but I can see all the tiles' implementations are in `tiles.js`
