### ISSUE TITLE
Automatically Test Game

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/labyrinth#46]
Sometimes, the game does not load e.g. in #42.
It would be good to have a server e.g. travis-ci.org to test the game for

- [x] correctness of syntax
- [x] loading without errors
- [x] code styling
- [x] enable travis ci

This way, every new commit will be tested and we can find the error before we deploy the game.

**Comment by abishekvashok** [comment]
@niccokunzmann  `code styling` is currently done by coala, should we move for another solution?

**Comment by niccokunzmann** [comment]
Sounds good. However, I do not see a coala-instance running on this projects. How can we activate coala for this project?

**Comment by abishekvashok** [comment]
@niccokunzmann coala runs on travis ci  and is running in each travis ci build currently

**Comment by niccokunzmann** [comment]
Travis is not activated.

**Comment by abishekvashok** [comment]
@niccokunzmann just activate it, I added all related code in #4

**Comment by niccokunzmann** [comment]
I can not I do not have admin rights. Who has them?

**Comment by abishekvashok** [comment]
This one is for @mariobehling then @niccokunzmann

**Comment by abishekvashok** [comment]
Since the conference is over, pinging @mariobehling

**Comment by 0x48piraj** [comment]
I think I can write **selenium unit tests for checking if our game loads without any error** :wine_glass: 

Ping @niccokunzmann @abishekvashok :100:

**Comment by YashKumarVerma** [comment]
More info here

http://www.seleniumhq.org/docs/01_introducing_selenium.jsp#test-automation-for-web-applications

**Comment by 0x48piraj** [comment]
Good Reference. I'm using selenium for a long time though :wink:

**Comment by abishekvashok** [comment]
@niccokunzmann 
> enable travis ci

It's not enabled yet!

**Comment by niccokunzmann** [comment]
I know. As time goes by, some hero will come along and press the right buttons!

**Comment by niccokunzmann** [comment]
#400 looks for syntax errors.
