### ISSUE TITLE
Bottom controls are not responding

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/labyrinth#463]
### Expected results

There is a way to control the character without using arrow keys.

### Actual results

The bottom controls do not seem to work.

### Steps to reproduce the issue

- click on the bottom-right
- click the controls
- nothing moves

**Comment by abishekvashok** [comment]
Would like to work on this, won't it improve the UI?

**Comment by niccokunzmann** [comment]
@abishekvashok So, you would like to claim the UI task for that, I think this matches the task description. Correct me if I am wrong.

**Comment by duttaditya18** [comment]
@niccokunzmann #576 fixed this.

**Comment by niccokunzmann** [comment]
Thanks
