### ISSUE TITLE
Alert popup overwhelmed the game

### ISSUE THREAD

**Issue by Ploypiti** [fossasia/labyrinth#467]
### Expected results
Continue playing without pressing _ok_ or _enter_ when the alert pops up and the alert **shouldn't** overlap the tiles; something like this:

![image](https://user-images.githubusercontent.com/32614202/34906941-5ed52d5e-f8a9-11e7-9e95-302cbc3cd2bb.png)
### Actual results
Alerts appears too often so that it's somehow annoying to press enter everywhere you go, it ruins the overall UX as well, the game focuses on _tiles_ not popups.
### Implementation/Solution Ideas
Moving the popup aside and remove the overlapping parts. Although since if it moved aside, the popup BG would blend with the game BG, we could make the popup more noticeable, eg. change the color or move it to the top, but I think it would require the player to slides to read the whole message, and it's not healthy for user experience.

![image](https://user-images.githubusercontent.com/32614202/34907087-c86c01c8-f8ab-11e7-81bc-975c6f8ed0fb.png)

### Would you like to work on this
Yes, open to suggestion.

**Comment by niccokunzmann** [comment]
@Ploypiti Thanks, this is a very clear description.
