### ISSUE TITLE
Game restarting

### ISSUE THREAD

**Issue by samyakbvs** [fossasia/labyrinth#468]
When the player moves on the tile that is located on the top of the guitar tile the game restarts

I would like to collaborate with someone on this issue

**Comment by niccokunzmann** [comment]
If this is the goal tile, I might change it working on #161 but it is uncertain when I will finish with this.

**Comment by abishekvashok** [comment]
@niccokunzmann yes

**Comment by arjunpandey2003** [comment]
@samyakbvs i am open for collab

**Comment by samyakbvs** [comment]
Sure @arjunpandey2003

**Comment by niccokunzmann** [comment]
resolved. #470
