### ISSUE TITLE
Add something valuable into tiles.

### ISSUE THREAD

**Issue by STEdirisuriya** [fossasia/labyrinth#469]
### Expected results
Add a something valuable fact into tiles like this tile which created by me.
![image](https://user-images.githubusercontent.com/33794760/34907772-a3264056-f8a9-11e7-9512-96d5c2ee0394.png)
In addition to having fun, let's give something relevant to education for kids and adults both.

### Actual results
No valuable things showing.

### Steps to reproduce the issue
we can make message box in to tiles, and replace with before text into valuable text. 

### Implementation/Solution Ideas
This is very important and valuable thing for all game players. 
### Would you like to work on this
 I am working

**Comment by duttaditya18** [comment]
@STEdirisuriya That looks like too much text. Any ideas to improve the design?
@Ploypiti Do you have any ideas?

**Comment by Ploypiti** [comment]
@duttaditya18 In my opinion, I think not all player are willing to take a history class or whatnot while playing the game. Also too much text would ruin the UX, refers to #467 if we're changing the alert UI, it's possible to add longer text.

**Comment by abishekvashok** [comment]
I think this can be safely closed.
