### ISSUE TITLE
Add property for Github Symbol

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/labyrinth#471]
### Expected results
On hovering over the GitHub symbol in "Follow us on" the colour should change .
### Actual results
On hovering over the GitHub symbol in "Follow us on" the colour does not change.
### Implementation/Solution Ideas
Add hover property for GitHub symbol. 
### Would you like to work on this
Yes

**Comment by niccokunzmann** [comment]
@harsh-jindal Please close if this is resolved.
