### ISSUE TITLE
center align caption of how to play site.

### ISSUE THREAD

**Issue by STEdirisuriya** [fossasia/labyrinth#477]
### Expected results
center aligned caption of how to play site.
![image](https://user-images.githubusercontent.com/33794760/34909444-1775e0ca-f8c7-11e7-9f45-0137b1ae9fa1.png)

### Actual results
slightly not centered.

### Steps to reproduce the issue
update js file related to that.

### Would you like to work on this
anyone work please @niccokunzmann 
I suggest this for @Ploypiti , because she made this. and she know this correctly.

**Comment by tanya-vedi** [comment]
Can I take this issue?

**Comment by niccokunzmann** [comment]
@tanya-vedi Thanks for your contribution. I checked and to fully close this, we also need to remove the width attribute http://rawgit.com/fossasia/labyrinth/master/css/stylesheet.css line 139 otherwise the header is of fixed size.

**Comment by tanya-vedi** [comment]
Sure! I'll do that.

**Comment by niccokunzmann** [comment]
I consider this one solved, thanks @tanya-vedi ! If you like to contribute more, you are always welcome. You can choose among tasks and issues. https://github.com/fossasia/labyrinth/tree/master/tasks

**Comment by niccokunzmann** [comment]
You can find us in the chat.. https://gitter.im/fossasia/labyrinth
