### ISSUE TITLE
indent all files

### ISSUE THREAD

**Issue by STEdirisuriya** [fossasia/labyrinth#478]
### Expected results
indentation of all files

### Actual results
not indented.

### Would you like to work on this
I am working

**Comment by niccokunzmann** [comment]
Please create a style guide or something in the documentation. Other wise, we may get stylings back and forth and no agreement.

**Comment by STEdirisuriya** [comment]
@niccokunzmann I didn't get what are you saying

**Comment by niccokunzmann** [comment]
If you indent it with 4 spaces and the next person indents is with two spaces, all we get is merge conflicts and no improvement, so please document how we wish to have the files look like before you change them. Otherwise it is not objective.

**Comment by niccokunzmann** [comment]
please also see #98

**Comment by DNS-404** [comment]
Is this issue completely solved?

**Comment by abishekvashok** [comment]
Nope @DNS-404

**Comment by DNS-404** [comment]
Which files are left to be indented?? @abishekvashok

**Comment by niccokunzmann** [comment]
@DNS-404 Please check the files and if all are of the same, you can report and we close this.

**Comment by DNS-404** [comment]
Okay, I'll check them

**Comment by DNS-404** [comment]
Some files have been intended with 2 spaces, some with a tab etc. I'll correct them. What standard should I follow? I mean should there be 2 spaces or a tab space or 4 spaces? @niccokunzmann

**Comment by niccokunzmann** [comment]
@DNS-404 That is a good question. I think, there might be style guides out there. If we document the style, we can ensure that it will be used in the future, too. How would you like to go on? I do not have an answer.

**Comment by DNS-404** [comment]
How about i change the indentation to using tab space before lines and then add a documentation for the indentation style in README.md? I'll write proper rules.

**Comment by DNS-404** [comment]
@niccokunzmann Should I do it?

**Comment by niccokunzmann** [comment]
I prefer to use spaces. Sure, please go ahead.

**Comment by DNS-404** [comment]
Alright. I'll do it with 2 spaces.

**Comment by niccokunzmann** [comment]
Is that compatible with most of what the contributors use? Is it
compatible with the GitHub online editor?

**Comment by DNS-404** [comment]
@niccokunzmann 
Well, html pages have either tab spaces or 2 spaces and 4 spaces at a few places. Most of the css(and js files) is with 2 spaces. Some are with 4 spaces.
Overall, most of the indentation is done with 2 spaces so I think that is what most of the contributors use. And yes it is compatible with GitHub online editor.
So I think that using 2 spaces as standard indentation for the whole project would be fine. What do you say?

**Comment by niccokunzmann** [comment]
I think, this is a solid statement and you removed all my doubts.
Thanks. I think, you are informed and what you decide will be responsible.

**Comment by DNS-404** [comment]
😄 Okay then I'm working on it now.

**Comment by STEdirisuriya** [comment]
@niccokunzmann is the problem the document fixed?

**Comment by niccokunzmann** [comment]
@DNS-404 What do you think?

**Comment by DNS-404** [comment]
@STEdirisuriya No, I'm working on it. I have indented html files. Now I'm doing the same for javascript and css files. Then I'll add a document regarding the coding style followed.

**Comment by STEdirisuriya** [comment]
@DNS-404 Thanks
