### ISSUE TITLE
Improve contributors page

### ISSUE THREAD

**Issue by STEdirisuriya** [fossasia/labyrinth#479]
### Expected results
- [ ] Improve menubar in contributors page
![image](https://user-images.githubusercontent.com/33794760/34909541-08ea8090-f8c9-11e7-8391-44c3f05ba75b.png)
- [ ] Center images
- [ ] Add social links of contributors.

### Actual results
Lot of things that needs fix

### Steps to reproduce the issue
See other pages and add features from those.

### Would you like to work on this
oOpen to all

**Comment by niccokunzmann** [comment]
There was a style before. This one broke. If you have time, you can try out git binary search

**Comment by saarthakchats** [comment]
I am attempting to improve menu bar

**Comment by saarthakchats** [comment]
Done!, @niccokunzmann @STEdirisuriya 
Pls review

**Comment by saarthakchats** [comment]
Navbar added and images centered and look improved in my PR
