### ISSUE TITLE
Close issues automatically when PR is merged

### ISSUE THREAD

**Issue by DNS-404** [fossasia/labyrinth#483]
### Actual results

Error in PR template. In PR template it says
`
Related Issues or Pull Requests #
`
This does not let issues to close automatically.

### Expected results

Change this to -
`
Fixes #[Add issue number here]
`
This will close the issue automatically when PR is merged.

### Would you like to work on this
Yes

**Comment by Beta-King** [comment]
This cant work in all cases, what if someone just contributes to a big issue and doesnt solve it. Then this feature would just complicate the whole process !! I'd suggest you think of some alternative to solve this issue :D

**Comment by niccokunzmann** [comment]
Some pull requests contribute to issues, some close the issues.
Having fixes there closes all of them, I think. Maybe we can add a comment that if you do not fix the issue, you can delete "fixes" Also, sometimes they relate to pull requests as we merge fast and may have follow-up pull requests. I would like to have PRs somewhere in there. What do you think? How can be achieve this, too?

**Comment by niccokunzmann** [comment]
I do not like the `[]` brackets. Because they then to stay there. If we use `<>`, then they do not display.

**Comment by niccokunzmann** [comment]
Although there is one contribution, I would like more input from you all.

**Comment by DNS-404** [comment]
Should I make the changes and create another PR?

**Comment by niccokunzmann** [comment]
I do not know, if you agree, I invite you to make the changes. If you do not agree, please tell me your perspective. We can find something where we both agree to.

**Comment by DNS-404** [comment]
I agree that some pull requests contribute to issues and some close the issues.
What you said earlier was fine by me. Let’s add a comment saying that “if the issue isn’t fixed completely by this PR then delete “fixes” and just mention the related issue number”. Would that be alright?

**Comment by niccokunzmann** [comment]
Yes, that would be alright.
