### ISSUE TITLE
fix winter landscape

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/labyrinth#494]
### Expected results

I can reach winter landscape tile 1 , left to the goal tile

### Actual results

Unreachable and broken svg
https://github.com/kubami9/labyrinth-km-contribute/blob/cc3fe220100eafd6edeb91c2fdd8c80b6c51ebd0/tiles/rooms/floor/winter1.svg

### Steps to reproduce the issue

right up right up up - then, left is not working

### Implementation/Solution Ideas

- add door on other side of this landscape tile
- fix svg

Related: #466

**Comment by abishekvashok** [comment]
@niccokunzmann the tile's svg seems broken.

**Comment by kubami9** [comment]
Okay, I'm fixing it now. I'm gonna add some doors and I just realised that I broke svg by using `script` instead of `style` 😅
