### ISSUE TITLE
UI improvements and fixes

### ISSUE THREAD

**Issue by kubami9** [fossasia/labyrinth#519]
### Expected results
- [x] restart game button #566
- [x] change character (in game) button #566
- [x] rate us section/box
- [ ] add a settings window for all of these things (clearer: which things)

### Actual results
Bugged menu and no current features/improvements in game

### Implementation/Solution Ideas
Create button which restarts game after clicking, create button which lets you change character during game, add characters svg preview to drop-down menu, change menu displaying so it's not bugged.

### Would you like to work on this
Yes, I'm working on it with @STEdirisuriya

**Comment by kubami9** [comment]
Menu bug seemed to disappear, first time I see that bug disappears instead of getting out of nowhere 😂

**Comment by STEdirisuriya** [comment]
Add a way to change color theme.
- add this point as well
