### ISSUE TITLE
Goal tile does not show walls

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/labyrinth#52]
When I press up up right right, I get to the goal.
The goal tile creates a message that I reached the goal

What I would like to see, too is:
1. The walls of the tile activated when I see them
2. The ground which I stand on

**Comment by abishekvashok** [comment]
@niccokunzmann what has to be done for that I think the floor png is not being rendered.

**Comment by abishekvashok** [comment]
@niccokunzmann found that, it was due to function overriding. Working on it.
