### ISSUE TITLE
delete unlicensed file

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/labyrinth#524]
### Expected results

The_Miller_and_the_Brook_Schubert_arr_Liszt[Mp3Converter.net].mp3
is a duplicate and should be deleted

### Actual results

The_Miller_and_the_Brook_Schubert_arr_Liszt[Mp3Converter.net].mp3
is there: https://github.com/fossasia/labyrinth/tree/master/audio/background

#521

**Comment by arjunpandey2003** [comment]
I am working on it

**Comment by arjunpandey2003** [comment]
@niccokunzmann ther is a license there
I think, pls check

**Comment by niccokunzmann** [comment]
Yes, but the file is a duplicate. He uploaded the file twice and I merged to motivate more contributions.

**Comment by DNS-404** [comment]
I'd like to work on this if no one is.
