### ISSUE TITLE
Replace "key" as attribute for translations

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/labyrinth#526]
### Expected results

checking the HTML file, using key is not allows in many cases.
Please replace it with something else.

### Actual results

- Key is used for translations
- https://github.com/fossasia/labyrinth/pull/525/files#diff-0406cdc32e5ca9a7a6aa5092fc2dbfce - this is an error, silenced

### Steps to reproduce the issue

https://validator.w3.org/nu/ and validate the html files

### Implementation/Solution Ideas

- replace key with something correct
  - in html files
  - in translate.js
- unsilence the error https://github.com/fossasia/labyrinth/pull/525/files#diff-0406cdc32e5ca9a7a6aa5092fc2dbfce

**Comment by harsh-jindal** [comment]
@niccokunzmann I can try working on this.

**Comment by abishekvashok** [comment]
@harsh-jindal sure

**Comment by harsh-jindal** [comment]
@abishekvashok Could you tell me what does the key attribute in HTML do ? I tried searching about it but couldn't find anything.

**Comment by niccokunzmann** [comment]
@harsh-jindal Yes, there is no such attribute in HTML and we get errors because of this. 
The "key" attribute is used here: https://github.com/fossasia/labyrinth/blob/master/js/translate.js#L104 for translations. Maybe, we can use another attribute which is not invalid.

**Comment by niccokunzmann** [comment]
Still todo: enable the tests for the key attribute again
