### ISSUE TITLE
[WIP]Reduce game and file sizes

### ISSUE THREAD

**Issue by saarthakchats** [fossasia/labyrinth#534]
### Firstly:-
All .png to be converted to .svg to reduce file size

- [x] boat.png

- [x] camel.png

- [x] choc.png

- [x] key.png

- [x] PoisonedMushrrom.png

- [x] Spoon.png

- [x] Cricketer.png

- [x] Discoverer.png

- [x] FreshAir.png

- [x] NailedIt.png

**Comment by saarthakchats** [comment]
I can't do all, help needed

**Comment by saarthakchats** [comment]
@niccokunzmann 
What do you think?

**Comment by samyakbvs** [comment]
I can do some of them

**Comment by saarthakchats** [comment]
I have done all

**Comment by saarthakchats** [comment]
@samyakbvs
