### ISSUE TITLE
Deploy Every PR on Surge

### ISSUE THREAD

**Issue by YashKumarVerma** [fossasia/labyrinth#540]
### Expected results
Automatically generate previews for PR

### Actual results
PR from branches other than gh-pages need to be uploaded somewhere else

### Steps to reproduce the issue
- Add surge.sh integration

### Would you like to work on this
Yes, but need assistance

**Comment by duttaditya18** [comment]
@niccokunzmann This is not documentation. This is a "Feature Request". @YashKumarVerma wants to make a script to automatically upload the file to [surge.sh](https://surge.sh).

**Comment by niccokunzmann** [comment]
@duttaditya18 I understood that it deploys the documentation, added new feature.

**Comment by YashKumarVerma** [comment]
deploys the documentation 😕 
um, i think the documentation tag should be removed 😄
