### ISSUE TITLE
Ferris wheel bug

### ISSUE THREAD

**Issue by thebigtrip** [fossasia/labyrinth#549]
i found a bug 
https://screenshots.firefox.com/84fZsHGYOvYmTwcF/rawgit.com

**Comment by abishekvashok** [comment]
That tile isnt correct. Where shave you seen it, how to reporoduce?

**Comment by thebigtrip** [comment]
the bug was two tiles down and two tiles to the left of the spawnpoint

**Comment by thebigtrip** [comment]
the ferris wheel kept going in a wide circle instead of staying in one place

**Comment by niccokunzmann** [comment]
If you edit it with inkscape, you can set the rotation center of this wheel. That should fix it, guess.

**Comment by abishekvashok** [comment]
Closing in favour of #641
