### ISSUE TITLE
[WEEKATHON]  International Labyrinth-Hackathon

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/labyrinth#552]
### Expected results

We want to organize a labyrinth hackathon for 9 days, spanning 2 weekends.

### Actual results

Date:
- Should be between April and Begin of June @0x48piraj
Topics:
- tasks for easy introduction
  - the gci tasks are for a contest including checking that things are done propertly
  - we need some tasks for those who like to contribute but without a competitive component and focus on helping
  - How can we use the GCI tasks and how can be provide feedback and guidance to newcomers?

### Implementation/Solution Ideas

- [ ] a website to send around #733
- [ ] a poster to print out

### Would you like to work on this

yes, please tell us if you like to take part or what you would like to do

Topics for this please in an other issue, link it here. This is about organizing it.

**Comment by Ploypiti** [comment]
Can I work on the poster design?

**Comment by duttaditya18** [comment]
@Ploypiti Anyone can work on it! And we can have various posters made by different people.

**Comment by niccokunzmann** [comment]
Sure, feel free to help :)

**Comment by duttaditya18** [comment]
>GCI tasks - need to make a new folder / docs for that

@niccokunzmann What is that supposed to mean?

**Comment by niccokunzmann** [comment]
@duttaditya18 I updated it. Is it clearer?

**Comment by abishekvashok** [comment]
Can we have it from `Maybe from 26th april to 3rd may.`

**Comment by 0x48piraj** [comment]
I and @abishekvashok can create some tasks, like we did for meilix.

@abishekvashok you in ?

**Comment by Ploypiti** [comment]
8.5x11 in (Us letter) poster, doing my best on this! Although if you have any idea for improvement it's cool. More details can be added, but currently, there aren't many details to add besides date & website. Website URL's still missing, I think we can use eventyay or gh-pages url or something.

![labyrinth hackathon](https://user-images.githubusercontent.com/32614202/35132218-a6ed59e8-fcfc-11e7-9e11-6937a10cd17f.jpg)

**Comment by duttaditya18** [comment]
@Ploypiti that looks absolutely amazing! Can there be something more Labyrinth-esque in place of the robot thing there is?

It looks amazing anyways! No need to change that if you don't feel like it.

**Comment by Ploypiti** [comment]
@duttaditya18 Thanks! (First of all, it's not a robot, it's a **MANIKIN**) I'll try to stuff some labyrinth vector/image that'd fit the design, BUT I'm afraid it'll mess up the design, let's see tho.

**Comment by vaibhavsingh97** [comment]
@Ploypiti You have got some aweomse design skills 😍

**Comment by niccokunzmann** [comment]
@Ploypiti Thanks!

If you used CC-BY content, please put a small small note at the bottom of the page, e.g. in gray. You can license the poster under CC-BY and your name, too.

**Comment by Ploypiti** [comment]
@vaibhavsingh97 Thanks!
@niccokunzmann The artworks were hand drawn and the images are from unsplash.com which attribute is not required :)

**Comment by duttaditya18** [comment]
@Ploypiti, even though attribution is not required, we can still have a small text at the bottom saying that the artwork is from unsplash.

**Comment by duttaditya18** [comment]
We need to get a website for this event. I will make a PR with a skeleton layout in a few hours.

**Comment by naveentherocker** [comment]
Anybody willing to work on the Website, I can collaborate with you.

**Comment by niccokunzmann** [comment]
I will fill in some text into the skeleton once it is there.

**Comment by duttaditya18** [comment]
@Ploypiti Are you done?

**Comment by niccokunzmann** [comment]
Hi @Ploypiti Thanks for your site, it looks great. I created https://github.com/fossasia/labyrinth/pull/732 to protect you and the labyrinth from Intellectual Property rights problems. I must say I am not a lawyer and I do not know the contract you made to get the files. Thus, I am not 100% sure at all and in any way with all licenses we have in this project. However, I do not want [evanto](https://sites.envato.com/) who created the files to find them in this project. This might be problematic for you and for FOSSASIA. If you bought them I am sure they do not allow anyone on the Internet to sell, modify and use their files without paying. Thus, GPL can not be applied to the files. We may proceed to use your site. I created https://github.com/fossasia/labyrinth/pull/733 which puts you in charge of the website you created until we host it in the labyrinth (which may never be the case because it just works well with your site). To let this go smoothly, you can invite other people to have write access to your repository.

**Comment by niccokunzmann** [comment]
@Ploypiti Would it be ok for you to add this to the poster:  

> ![](https://i.creativecommons.org/l/by-sa/4.0/88x31.png) Ploypiti Piyaprapan

or 

> CC-BY-SA by Ploypiti Piyaprapan

? Then, we can modify it, too.

**Comment by Ploypiti** [comment]
Say I paid for it @niccokunzmann, maybe you need to read the comment I left on #732?

**Comment by niccokunzmann** [comment]
@all, what do you think, we need for the Weekathon? Please create issues with `[WEEKATHON]` in the title: https://github.com/fossasia/labyrinth/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+WEEKATHON+in%3Atitle

**Comment by Ploypiti** [comment]
Nope.

![image](https://user-images.githubusercontent.com/32614202/37211169-a8b6b762-23dd-11e8-81b3-810790110283.png)
