### ISSUE TITLE
Few Design issues.

### ISSUE THREAD

**Issue by duttaditya18** [fossasia/labyrinth#557]
* [x] Make the text on top nav white.
* [x] Use Materialize.css buttons in the sidebar.
* [x] Use Materialize.css buttons in the Language Selector.
* [x] Add transition on YouTube and GitHub icons.
* [ ] Add back the old text logo as it better suited the overall style.
* [x] Remove hover effect on Player Moved and other statistics.
* [x] Center align icons in sidebar `li`.

### Would you like to work on this
Yup!

**Comment by niccokunzmann** [comment]
#562 reverted some changes
