### ISSUE TITLE
center those icons

### ISSUE THREAD

**Issue by STEdirisuriya** [fossasia/labyrinth#578]
### Expected results
center language translate icons.

### Actual results
it's not centered

### Steps to reproduce the issue
it's centered earlier So I think some of code missing or replace.

### Implementation/Solution Ideas
Please check it

### Would you like to work on this
open to anyone 

![image](https://user-images.githubusercontent.com/33794760/35038407-c74d268a-fba0-11e7-90a4-214b1a3cd37f.png)

**Comment by duttaditya18** [comment]
@STEdirisuriya I think it is centered. Check again.

**Comment by duttaditya18** [comment]
@niccokunzmann This was fixed in #574.

**Comment by niccokunzmann** [comment]
Thanks for the notification.
