### ISSUE TITLE
Add buttons to simulate arrow keys in mobile

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/labyrinth#58]
Let's make it playable at the mobile as well. Add buttons to simulate arrow keys in keyboard so that we can play it on mobile as well.

**Comment by YashKumarVerma** [comment]
are u working on it @abishekvashok

**Comment by niccokunzmann** [comment]
A hint: You can use the methods of the player canMoveLeft, ... https://github.com/fossasia/labyrinth/blob/master/js/player.js#L13 to show  the buttons which can be used and hide the others.

**Comment by niccokunzmann** [comment]
@YashKumarVerma You can start and share the pull request with us. If people want to collaborate, they can do it, then.

**Comment by abishekvashok** [comment]
@YashKumarVerma no, you can carry on with this. Also be sure to use the existing methods as @niccokunzmann pointed out.

**Comment by YashKumarVerma** [comment]
@niccokunzmann can we include jquery into the project ?

**Comment by abishekvashok** [comment]
Is that required @YashKumarVerma. We can go if u and nicco wants.

**Comment by niccokunzmann** [comment]
If you think that is a good choice, we can include jquery. If so, please copy it into the JS folder so we also play this game offline and ship it as an app without or with low bandwidth.

**Comment by niccokunzmann** [comment]
I think, adding the buttons in general is an improvement, showing and hiding them is another improvement and doing one does not mean the other needs to be done by the same person.

**Comment by YashKumarVerma** [comment]
working on it .

Claiming 🔥
