### ISSUE TITLE
Can move through mushroom tile wall

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/labyrinth#588]
### Expected results

cannot move through mushroom tile wall.

### Actual results

can move through mushroom tile wall.
in the forest level

### Implementation/Solution Ideas

- use door
- make wall functionality

**Comment by duttaditya18** [comment]
Sorry for this but how do I get to a new level?

**Comment by niccokunzmann** [comment]
When you get to the goal tile right up right up up or so, you can choose
the other level.

**Comment by duttaditya18** [comment]
@niccokunzmann Oh okay! Thanks!
