### ISSUE TITLE
Fix code lint erros to increase code quality

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/labyrinth#6]
Increase code quality by fixing the following lint errors:
- [x] >index.html
|  1| <!doctype·html>
|    | [MAJOR] HTMLLintBear:
|    | Document Type: Use HTML5: Change "<!doctype html>" to "`<!DOCTYPE html>`".

- [x] >i|   2| ····<script··src="js/tiles.js"·type="text/javascript"></script>
|    | [MAJOR] HTMLLintBear:
|    | Extra whitespace: Use whitespaces only where expected and be consistent: Remove the extra whitespaces.

- [x] >i|   3| ····<script··src="js/levels.js"·type="text/javascript"></script>
|    | [MAJOR] HTMLLintBear:
|    | type Attributes: The default type for script tags is "text/javascript" so it can be safely omitted: Remove the type attribute from the script tag.

- [x] >iindex.html
|   4| ····<script··src="js/player.js"·type="text/javascript"></script>
|    | [MAJOR] HTMLLintBear:
|    | Extra whitespace: Use whitespaces only where expected and be consistent: Remove the extra whitespaces.

- [x] >iindex.html
|   7| ····<script··src="js/player.js"·type="text/javascript"></script>
|    | [MAJOR] HTMLLintBear:
|    | type Attributes: The default type for script tags is "text/javascript" so it can be safely omitted: Remove the type attribute from the script tag.

- [x] >iindex.html
|   8| ····<script··src="js/gui.js"·type="text/javascript"></script>
|    | [MAJOR] HTMLLintBear:
|    | Extra whitespace: Use whitespaces only where expected and be consistent: Remove the extra whitespaces.

- [x] >iindex.html
|   8| ····<script··src="js/gui.js"·type="text/javascript"></script>
|    | [MAJOR] HTMLLintBear:
|    | type Attributes: The default type for script tags is "text/javascript" so it can be safely omitted: Remove the type attribute from the script tag.

- [x] >iindex.html
|   9| ····<script··src="js/level.js"·type="text/javascript"></script>
|    | [MAJOR] HTMLLintBear:
|    | type Attributes: The default type for script tags is "text/javascript" so it can be safely omitted: Remove the type attribute from the script tag.

- [x] >ijs/gui.js
|  18| ······player.moveLeft()
|    | [NORMAL] JSHintBear:
|    | Missing semicolon.

- [x] >ijs/gui.js
|  19| ····};
|    | [NORMAL] JSHintBear:
|    | Unnecessary semicolon.

- [x] >ijs/gui.js
|  24| ······player.moveRight()
|    | [NORMAL] JSHintBear:
|    | Missing semicolon.

- [x] >ijs/gui.js
|  25| ····};
|    | [NORMAL] JSHintBear:
|    | Unnecessary semicolon.

- [x] >ijs/gui.js
|  30| ······player.moveUp()
|    | [NORMAL] JSHintBear:
|    | Missing semicolon.

- [x] >ijs/gui.js
|  31| ····};
|    | [NORMAL] JSHintBear:
|    | Unnecessary semicolon.

- [x] >ijs/gui.js
|  36| ······player.moveDown()
|    | [NORMAL] JSHintBear:
|    | Missing semicolon.

- [x] >ijs/gui.js
|  37| ····};
|    | [NORMAL] JSHintBear:
|    | Unnecessary semicolon.

- [x] >ijs/gui.js
|  43| }
|    | [NORMAL] JSHintBear:
|    | Missing semicolon.

- [x] >ijs/gui.js
|   9| ··level·=·createTestLevel();
|    | [NORMAL] JSHintBear:
|    | 'createTestLevel' is not defined.

- [x] >ijs/gui.js
|  11| ··player·=·newPlayer();
|    | [NORMAL] JSHintBear:
|    | 'newPlayer' is not defined.

- [x] >ijs/level.js
|   2| const·tileWidth·=·429.544;·//·px,·real·width
|    | [NORMAL] JSHintBear:
|    | 'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).

- [x] >ijs/level.js
|   3| const·tileHeight·=·256.314;·//·px
|    | [NORMAL] JSHintBear:
|    | 'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).

- [x] >ijs/level.js
|  16| ····}
|    | [NORMAL] JSHintBear:
|    | Missing semicolon.

- [x] >js/level.js
|  23| ········const·position·=·{"x":·x,·"y":·y};
|    | [NORMAL] JSHintBear:
|    | 'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).

- [x] >js/level.js
|  24| ········const·pixelPosition·=·me.indexToPosition(position);
|    | [NORMAL] JSHintBear:
|    | 'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).

- [x] >js/level.js
|  39| ··}
|    | [NORMAL] JSHintBear:
|    | Missing semicolon.

- [x] >js/level.js
|  42| ··}
|    | [NORMAL] JSHintBear:
|    | Missing semicolon.

- [x] >js/level.js
|  45| ··}
|    | [NORMAL] JSHintBear:
|    | Missing semicolon.

- [x] >js/level.js
|  57| ······const·position·=·{"x":·x,·"y":·y};
|    | [NORMAL] JSHintBear:
|    | 'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).

- [ ] >js/level.js
|  61| ··if·(this.startTile·==·null)·{
|    | [NORMAL] JSHintBear:
|    | Expected '===' and instead saw '=='.

- [ ] >js/level.js
|  36| ······return·NullTile;
|    | [NORMAL] JSHintBear:
|    | 'NullTile' is not defined.

- [ ] >js/level.js
|   5| function·Level(specification)
|    | [NORMAL] JSHintBear:
|    | 'Level' is defined but never used.

- [ ] >js/player.js
|  43| ··}
|    | [NORMAL] JSHintBear:
|    | Missing semicolon.

- [ ] >js/player.js
|  46| ··}
|    | [NORMAL] JSHintBear:
|    | Missing semicolon.

- [ ] >js/player.js
|   7| ··this.currentTile·=·NullTile;
|    | [NORMAL] JSHintBear:
|    | 'NullTile' is not defined.

- [ ] >js/player.js
|   2| function·newPlayer()·{
|    | [NORMAL] JSHintBear:
|    | 'newPlayer' is defined but never used.

- [ ] >js/loading.js
|   6| ····if·(xmlHttp.readyState·==·4)·{
|    | [NORMAL] JSHintBear:
|    | Expected '===' and instead saw '=='.

- [ ] >js/loading.js
|   7| ······if·(xmlHttp.status·==·200)·{
|    | [NORMAL] JSHintBear:
|    | Expected '===' and instead saw '=='.

- [ ] >js/loading.js
|  13| ··}
|    | [NORMAL] JSHintBear:
|    | Missing semicolon.

- [ ] >js/loading.js
|   1| function·httpGetAsync(theUrl,·callback)
|    | [NORMAL] JSHintBear:
|    | 'httpGetAsync' is defined but never used.

- [ ] >js/tiles.js
|   2| const·NullTile·=·{
|    | [NORMAL] JSHintBear:
|    | 'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).

- [ ] >js/tiles.js
|   3| ··canEnterFromTheTop:·function(player)·{return·false;},
|    | [NORMAL] JSHintBear:
|    | 'player' is defined but never used.

- [ ] >js/tiles.js
|   4| ··canEnterFromTheBottom:·function(player)·{return·false;},
|    | [NORMAL] JSHintBear:
|    | 'player' is defined but never used.

- [ ] >js/tiles.js
|   5| ··canEnterFromTheRight:·function(player)·{return·false;},
|    | [NORMAL] JSHintBear:
|    | 'player' is defined but never used.

- [ ] >js/tiles.js
|   6| ··canEnterFromTheLeft:·function(player)·{return·false;},
|    | [NORMAL] JSHintBear:
|    | 'player' is defined but never used.

- [ ] >js/tiles.js
|   7| ··playerLeaves:·function(player){},
|    | [NORMAL] JSHintBear:
|    | 'player' is defined but never used.

- [ ] >js/tiles.js
|   8| ··placeAtIn:·function(){return·this},
|    | [NORMAL] JSHintBear:
|    | Missing semicolon.

- [ ] >js/tiles.js
|  15| }
|    | [NORMAL] JSHintBear:
|    | Missing semicolon.

- [ ] >js/tiles.js
|  24| ··}
|    | [NORMAL] JSHintBear:
|    | Missing semicolon.

- [ ] >js/tiles.js
|  35| };
|    | [NORMAL] JSHintBear:
|    | Unnecessary semicolon.

- [ ] >js/tiles.js
|  56| ImageCollection.prototype.playerEnters·=·function(player)·{
|    | [NORMAL] JSHintBear:
|    | 'player' is defined but never used.

- [ ] >js/tiles.js
|  59| ImageCollection.prototype.playerLeaves·=·function(player)·{
|    | [NORMAL] JSHintBear:
|    | 'player' is defined but never used.

- [ ] >js/tiles.js
|  72| };
|    | [NORMAL] JSHintBear:
|    | Unnecessary semicolon.

- [ ] >js/tiles.js
| 102| const·OpenDoors·=·{
|    | [NORMAL] JSHintBear:
|    | 'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).

- [ ] >js/tiles.js
| 104| ··canEnterFromTheTop:·function(player)·{return·true;},
|    | [NORMAL] JSHintBear:
|    | 'player' is defined but never used.

- [ ] >js/tiles.js
| 105| ··canEnterFromTheBottom:·function(player)·{return·true;},
|    | [NORMAL] JSHintBear:
|    | 'player' is defined but never used.

- [ ] >js/tiles.js
| 106| ··canEnterFromTheRight:·function(player)·{return·true;},
|    | [NORMAL] JSHintBear:
|    | 'player' is defined but never used.

- [ ] >js/tiles.js
| 107| ··canEnterFromTheLeft:·function(player)·{return·true;},
|    | [NORMAL] JSHintBear:
|    | 'player' is defined but never used.

- [ ] >js/tiles.js
| 108| ··canLeaveToTheTop:·function(player)·{return·true;},
|    | [NORMAL] JSHintBear:
|    | 'player' is defined but never used.

- [ ] >js/tiles.js
| 109| ··canLeaveToTheBottom:·function(player)·{return·true;},
|    | [NORMAL] JSHintBear:
|    | 'player' is defined but never used.

- [ ] >js/tiles.js
| 110| ··canLeaveToTheRight:·function(player)·{return·true;},
|    | [NORMAL] JSHintBear:
|    | 'player' is defined but never used.

- [ ] >js/tiles.js

| 111| ··canLeaveToTheLeft:·function(player)·{return·true;},
|    | [NORMAL] JSHintBear:
|    | 'player' is defined but never used.

- [ ] >js/tiles.js

| 112| ··viewFromTheTop:·function(player)·{
|    | [NORMAL] JSHintBear:
|    | 'player' is defined but never used.

- [ ] >js/tiles.js
| 115| ··viewFromTheLeft:·function(player)·{
|    | [NORMAL] JSHintBear:
|    | 'player' is defined but never used.

- [ ] >js/tiles.js
| 117| ··viewFromTheRight:·function(player)·{
|    | [NORMAL] JSHintBear:
|    | 'player' is defined but never used.

- [ ] >js/tiles.js
| 120| ··viewFromTheBottom:·function(player)·{
|    | [NORMAL] JSHintBear:
|    | 'player' is defined but never used.

- [ ] >js/tiles.js
| 122| ··whenPlayerLeaves:·function(player){
|    | [NORMAL] JSHintBear:
|    | 'player' is defined but never used.

- [ ] >js/tiles.js
| 124| ··whenPlayerEnters:·function(player){
|    | [NORMAL] JSHintBear:
|    | 'player' is defined but never used.

- [ ] >js/tiles.js
| 147| const·door·=·{
|    | [NORMAL] JSHintBear:
|    | 'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).

- [ ] >js/tiles.js
| 150| ····canEnterFromTheTop:·function(player)·{return·false;},
|    | [NORMAL] JSHintBear:
|    | 'player' is defined but never used.

- [ ] >js/tiles.js
| 151| ····canLeaveToTheTop:·function(player)·{return·false;},
|    | [NORMAL] JSHintBear:
|    | 'player' is defined but never used.

- [ ] >js/tiles.js
| 159| ····canEnterFromTheRight()·{return·false;},
|    | [NORMAL] JSHintBear:
|    | 'concise methods' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).

- [ ] >js/tiles.js
| 160| ····canLeaveToTheRight()·{return·false;},
|    | [NORMAL] JSHintBear:
|    | 'concise methods' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).

- [ ] >js/tiles.js
| 168| ····canEnterFromTheRight()·{return·false;},
|    | [NORMAL] JSHintBear:
|    | 'concise methods' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).

- [ ] >js/tiles.js
| 169| ····canLeaveToTheRight()·{return·false;},
|    | [NORMAL] JSHintBear:
|    | 'concise methods' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).

- [ ] >js/tiles.js
| 170| ····canEnterFromTheTop:·function(player)·{return·false;},
|    | [NORMAL] JSHintBear:
|    | 'player' is defined but never used.

- [ ] >js/tiles.js
| 171| ····canLeaveToTheTop:·function(player)·{return·false;},
|    | [NORMAL] JSHintBear:
|    | 'player' is defined but never used.

- [ ] >js/tiles.js
| 178| }
|    | [NORMAL] JSHintBear:
|    | Missing semicolon.

- [ ] >js/tiles.js
|   2| const·NullTile·=·{
|    | [NORMAL] JSHintBear:
|    | 'NullTile' is defined but never used.

- [ ] >js/tiles.js
|  17| function·PlayerStartsAt(tileSpecification)·{
|    | [NORMAL] JSHintBear:
|    | 'PlayerStartsAt' is defined but never used.

- [ ] >js/tiles.js
| 147| const·door·=·{
|    | [NORMAL] JSHintBear:
|    | 'door' is defined but never used.

- [ ] >js/levels.js
|   3| ··return·new·Level([
|    | [NORMAL] JSHintBear:
|    | 'Level' is not defined.

- [ ] >js/levels.js
|   4| ····[door.none,·door.right,·door.right,·door.right,·door.right,·door.none],
|    | [NORMAL] JSHintBear:
|    | 'door' is not defined.

- [ ] >js/levels.js
|   4| ····[door.none,·door.right,·door.right,·door.right,·door.right,·door.none],
|    | [NORMAL] JSHintBear:
|    | 'door' is not defined.

- [ ] >js/levels.js
|    | [NORMAL] JSHintBear:
|    | 'door' is not defined.

- [ ] >js/levels.js
|   4| ····[door.none,·door.right,·door.right,·door.right,·door.right,·door.none],
|    | [NORMAL] JSHintBear:
|    | 'door' is not defined.

- [ ] >js/levels.js
|   4| ····[door.none,·door.right,·door.right,·door.right,·door.right,·door.none],
|    | [NORMAL] JSHintBear:
|    | 'door' is not defined.

- [ ] >js/levels.js
|   4| ····[door.none,·door.right,·door.right,·door.right,·door.right,·door.none],
|    | [NORMAL] JSHintBear:
|    | 'door' is not defined.

- [ ] >js/levels.js
|   5| ····[door.none,·door.top,·door.both,·door.both,·door.both,·door.top],
|    | [NORMAL] JSHintBear:
|    | 'door' is not defined.

- [ ] >js/levels.js
|   5| ····[door.none,·door.top,·door.both,·door.both,·door.both,·door.top],
|    | [NORMAL] JSHintBear:
|    | 'door' is not defined.

- [ ] >js/levels.js
|   5| ····[door.none,·door.top,·door.both,·door.both,·door.both,·door.top],
|    | [NORMAL] JSHintBear:
|    | 'door' is not defined.

- [ ] >js/levels.js
|   5| ····[door.none,·door.top,·door.both,·door.both,·door.both,·door.top],
|    | [NORMAL] JSHintBear:
|    | 'door' is not defined.

- [ ] >js/levels.js
|   5| ····[door.none,·door.top,·door.both,·door.both,·door.both,·door.top],
|    | [NORMAL] JSHintBear:
|    | 'door' is not defined.

- [ ] >js/levels.js
|   5| ····[door.none,·door.top,·door.both,·door.both,·door.both,·door.top],
|    | [NORMAL] JSHintBear:
|    | 'door' is not defined.

- [ ] >js/levels.js
|   6| ····[door.none,·door.top,·PlayerStartsAt(door.both),·door.both,·door.both,·door.top],
|    | [NORMAL] JSHintBear:
|    | 'door' is not defined.

- [ ] >js/levels.js
|   6| ····[door.none,·door.top,·PlayerStartsAt(door.both),·door.both,·door.both,·door.top],
|    | [NORMAL] JSHintBear:
|    | 'door' is not defined.

- [ ] >js/levels.js
|   6| ····[door.none,·door.top,·PlayerStartsAt(door.both),·door.both,·door.both,·door.top],
|    | [NORMAL] JSHintBear:
|    | 'door' is not defined.

- [ ] >js/levels.js
|   6| ····[door.none,·door.top,·PlayerStartsAt(door.both),·door.both,·door.both,·door.top],
|    | [NORMAL] JSHintBear:
|    | 'door' is not defined.

- [ ] >js/levels.js
|   6| ····[door.none,·door.top,·PlayerStartsAt(door.both),·door.both,·door.both,·door.top],
|    | [NORMAL] JSHintBear:
|    | 'door' is not defined.

- [ ] >js/levels.js
|   6| ····[door.none,·door.top,·PlayerStartsAt(door.both),·door.both,·door.both,·door.top],
|    | [NORMAL] JSHintBear:
|    | 'door' is not defined.

- [ ] >js/levels.js
|   7| ····[door.none,·door.top,·door.both,·door.both,·door.both,·door.top],
|    | [NORMAL] JSHintBear:
|    | 'door' is not defined.

- [ ] >js/levels.js
|   7| ····[door.none,·door.top,·door.both,·door.both,·door.both,·door.top],
|    | [NORMAL] JSHintBear:
|    | 'door' is not defined.

- [ ] >js/levels.js
|   7| ····[door.none,·door.top,·door.both,·door.both,·door.both,·door.top],
|    | [NORMAL] JSHintBear:
|    | 'door' is not defined.

- [ ] >js/levels.js
|   7| ····[door.none,·door.top,·door.both,·door.both,·door.both,·door.top],
|    | [NORMAL] JSHintBear:
|    | 'door' is not defined.

- [ ] >js/levels.js
|   7| ····[door.none,·door.top,·door.both,·door.both,·door.both,·door.top],
|    | [NORMAL] JSHintBear:
|    | 'door' is not defined.

- [ ] >js/levels.js
|   7| ····[door.none,·door.top,·door.both,·door.both,·door.both,·door.top],
|    | [NORMAL] JSHintBear:
|    | 'door' is not defined.

- [ ] >js/levels.js
|   8| ····[door.none,·door.top,·door.both,·door.both,·door.both,·door.top],
|    | [NORMAL] JSHintBear:
|    | 'door' is not defined.

- [ ] >js/levels.js
|   8| ····[door.none,·door.top,·door.both,·door.both,·door.both,·door.top],
|    | [NORMAL] JSHintBear:
|    | 'door' is not defined.

- [ ] >js/levels.js
|   8| ····[door.none,·door.top,·door.both,·door.both,·door.both,·door.top],
|    | [NORMAL] JSHintBear:
|    | 'door' is not defined.

- [ ] >js/levels.js
|   8| ····[door.none,·door.top,·door.both,·door.both,·door.both,·door.top],
|    | [NORMAL] JSHintBear:
|    | 'door' is not defined.

- [ ] >js/levels.js
|   8| ····[door.none,·door.top,·door.both,·door.both,·door.both,·door.top],
|    | [NORMAL] JSHintBear:
|    | 'door' is not defined.

- [ ] >js/levels.js
|   8| ····[door.none,·door.top,·door.both,·door.both,·door.both,·door.top],
|    | [NORMAL] JSHintBear:
|    | 'door' is not defined.

- [ ] >js/levels.js
|   9| ····[door.none,·door.top,·door.both,·door.both,·door.both,·door.top],
|    | [NORMAL] JSHintBear:
|    | 'door' is not defined.

- [ ] >js/levels.js
|   9| ····[door.none,·door.top,·door.both,·door.both,·door.both,·door.top],
|    | [NORMAL] JSHintBear:
|    | 'door' is not defined.

- [ ] >js/levels.js
|   9| ····[door.none,·door.top,·door.both,·door.both,·door.both,·door.top],
|    | [NORMAL] JSHintBear:
|    | 'door' is not defined.

- [ ] >js/levels.js
|   9| ····[door.none,·door.top,·door.both,·door.both,·door.both,·door.top],
|    | [NORMAL] JSHintBear:
|    | 'door' is not defined.

- [ ] >js/levels.js
|   9| ····[door.none,·door.top,·door.both,·door.both,·door.both,·door.top],
|    | [NORMAL] JSHintBear:
|    | 'door' is not defined.

- [ ] >js/levels.js
|   9| ····[door.none,·door.top,·door.both,·door.both,·door.both,·door.top],
|    | [NORMAL] JSHintBear:
|    | 'door' is not defined.

- [ ] >js/levels.js
|  10| ····[NullTile,·door.none,·door.none,·door.none,·door.none,·door.none],
|    | [NORMAL] JSHintBear:
|    | 'door' is not defined.

- [ ] >js/levels.js
|  10| ····[NullTile,·door.none,·door.none,·door.none,·door.none,·door.none],
|    | [NORMAL] JSHintBear:
|    | 'door' is not defined.

- [ ] >js/levels.js
|  10| ····[NullTile,·door.none,·door.none,·door.none,·door.none,·door.none],
|    | [NORMAL] JSHintBear:
|    | 'door' is not defined.

- [ ] >js/levels.js
|  10| ····[NullTile,·door.none,·door.none,·door.none,·door.none,·door.none],
|    | [NORMAL] JSHintBear:
|    | 'door' is not defined.

- [ ] >js/levels.js
|  10| ····[NullTile,·door.none,·door.none,·door.none,·door.none,·door.none],
|    | [NORMAL] JSHintBear:
|    | 'door' is not defined.

- [ ] >js/levels.js
|   6| ····[door.none,·door.top,·PlayerStartsAt(door.both),·door.both,·door.both,·door.top],
|    | [NORMAL] JSHintBear:
|    | 'PlayerStartsAt' is not defined.

- [ ] >js/levels.js
|  10| ····[NullTile,·door.none,·door.none,·door.none,·door.none,·door.none],
|    | [NORMAL] JSHintBear:
|    | 'NullTile' is not defined.

- [ ] >js/levels.js
|   1| function·createTestLevel()
|    | [NORMAL] JSHintBear:
|    | 'createTestLevel' is defined but never used.

(**Note:** A contributor is asked to fix only a about 7-10 lint errors and leave the rest for the other contributors as outlined in the GCI task)

**Comment by duttaditya18** [comment]
@abishekvashok Please tick the ones that have been completed.

**Comment by duttaditya18** [comment]
Tick 9 to 39 (#8 fixed them).

**Comment by abishekvashok** [comment]
Done 👌👌 thank-you

**Comment by duttaditya18** [comment]
@abishekvashok Cool!

**Comment by abishekvashok** [comment]
It's not completely fixed @xeon-zolt

**Comment by duttaditya18** [comment]
@naveentherocker Please do not do `Fixes #issue no.` on PRs that do not fully fix the issue.

**Comment by naveentherocker** [comment]
@duttaditya18 Oh sorry

**Comment by myfrom** [comment]
I will take the missing/unnecessary semicolons and undefined 'door' variable.

Also a question: would using 'esversion: 6' be a valid solution here or should the code be changed to es5?

**Comment by duttaditya18** [comment]
@myfrom Just ignore the `esversion: 6` error. It is there because the JSLint setup config did not have the argument to use ECMAScript 6 (cost with functions were introduced in ES6).

Do not change the code to be ES5 compatible. It would mess some stuff up.

**Comment by myfrom** [comment]
@duttaditya18 I can add that to the config, should I?

**Comment by duttaditya18** [comment]
@myfrom You can run the test again, but I'd recommend you to just ignore that error.

**Comment by myfrom** [comment]
Since we don't even use [loading.js](js/loading.js) should it stay or can we remove it?

**Comment by niccokunzmann** [comment]
Does it have code which should be used? If loading.js is not useful, we
can remove it.

**Comment by myfrom** [comment]
The code it contains is a helper function around XMLHttpRequest, I searched
other files and the function isn't used anywhere. I'll remove that file.

**Comment by niccokunzmann** [comment]
Removal sounds good to me, too.

**Comment by arjunpandey2003** [comment]
@abishekvashok can i also work on this issue

**Comment by myfrom** [comment]
I think we would need to run the checks again and edit the issue list as
when I was working on it, I found many of the ones not existing anymore and
new ones getting created

**Comment by abishekvashok** [comment]
I am gonna close this one. I will run the link tests and open up a new issue for the same.

**Comment by abishekvashok** [comment]
*lint
