### ISSUE TITLE
Bugged Images in Character Selector

### ISSUE THREAD

**Issue by NaviRocker** [fossasia/labyrinth#601]
### Expected results
Character Selector Working Properly
### Actual results
Few Images in Character Selector are Bugged
### Steps to reproduce the issue
Fix the Images
### Screenshot
![loj](https://user-images.githubusercontent.com/16055010/35110747-8dbf2314-fc9f-11e7-91d6-968482d5cb19.PNG)

### Would you like to work on this
I'll wait for few hours for others to claim. If no one Claims, I'll work on it.

**Comment by duttaditya18** [comment]
First work on implementing the character selector in a real game : #579

**Comment by STEdirisuriya** [comment]
@duttaditya18 If you can add a way to select them for play

**Comment by YashKumarVerma** [comment]
Page no longer exists. Therefore closing.
