### ISSUE TITLE
Image not displayed on "how to play" page

### ISSUE THREAD

**Issue by DNS-404** [fossasia/labyrinth#604]
### Expected results
Image should be displayed on how to play page.

### Actual results
Image is not displayed.

### Steps to reproduce the issue
Go to http://rawgit.com/fossasia/labyrinth/master/howtoplay.html

### Implementation/Solution Ideas
First of all, reference to the image file is not correct so have to change source of image. Then the dimension of image is not right. It has too much white space on sides. It should be cropped.

### Would you like to work on this
Yes

**Comment by abishekvashok** [comment]
Hey, I can see them
![screenshot_20180120_112253](https://user-images.githubusercontent.com/8947010/35180361-cbc4b774-fdd4-11e7-95cf-90f10ef90d5a.png)

Which ones are you referring to?

**Comment by DNS-404** [comment]
I just noticed that there are image reference issues with some more files. I'm correcting all of them.

**Comment by DNS-404** [comment]
This one -> below "How to play"
<img width="510" alt="screen shot 2018-01-20 at 11 27 10 am" src="https://user-images.githubusercontent.com/31174685/35180366-e8cf1256-fdd4-11e7-8e73-88809628dc5c.png">

**Comment by abishekvashok** [comment]
okay, pls proceed then
