### ISSUE TITLE
Direction buttons should show 45° rotated directions

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/labyrinth#607]
### Expected results

When I click on the running person in the bottom right, I would like to see direction buttons
which display the direction of the labyrinth.

### Actual results

I see buttons which work but they are 45° rotated so that I do not know where they lead.

### Implementation/Solution Ideas

Use another picture.

**Comment by DNS-404** [comment]
I would like to work on this. 😃

**Comment by niccokunzmann** [comment]
Thanks for telling us, please go ahead :)

**Comment by DNS-404** [comment]
If I use diagonal icons from some other source(say flaticon) then I would have to credit the author of those icons.

**Comment by niccokunzmann** [comment]
Yes. We have a credits page for that. Drawing an arrow is also something you can do yourself in inkscape.

**Comment by niccokunzmann** [comment]
Let's say: It depends on the license. Some may not be used, some are with credit, some are just free. If you create them yourself, you can decide.

**Comment by DNS-404** [comment]
Okay, I've never used inkscape before. Let's see.. I will either create the icons or take them from some source and credit the author in credits page.
