### ISSUE TITLE
Add a way for sign in to game and rate it. 

### ISSUE THREAD

**Issue by STEdirisuriya** [fossasia/labyrinth#618]
### Expected results
Add a way for sign in to game and rate it.  If not lot of points can add for one player.

### Actual results
Lot of points(ratings) can add for one player. 

### Steps to reproduce the issue
Add a way for sign in to game

### Implementation/Solution Ideas
Use gmail account instead or add a way for make a new account for game.

### Would you like to work on this
Open to anyone!

**Comment by himanshuc3** [comment]
Is this to be done using O-auth.

**Comment by rajdeepbharati** [comment]
@YashKumarVerma I'm interested in this issue. Should we use O-auth?

**Comment by STEdirisuriya** [comment]
@rajdeepbharati Go ahead! good luck.

**Comment by YashKumarVerma** [comment]
> @YashKumarVerma I'm interested in this issue. Should we use O-auth?

Yes
