### ISSUE TITLE
The flag for Polski not correctly sized!

### ISSUE THREAD

**Issue by STEdirisuriya** [fossasia/labyrinth#619]
### Expected results
Use a correct sized flag for show translations. 

### Actual results
Not centered correctly because it's not use correct measures of width and height. 

### Steps to reproduce the issue
When I add Sinhala translation I use flags for English and Sinhala from Wikipedia. Use imagem 255px X 128px sized. Download image from this place _(_https://en.wikipedia.org/wiki/Flag_of_England)_ and resize it to 255px X 128px . It will help you to make it centered.

### Would you like to work on this
@kubami9 can work on this. He added Polski translation So I think he can do this. If he didn't do this within 2 days open this to others.

**Comment by STEdirisuriya** [comment]
@kubami9 What's your status

**Comment by kubami9** [comment]
Sorry, had some issues with my laptop I'm back now doing all the work from scratch again
