### ISSUE TITLE
Make Changes to UI_Identity.md

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/labyrinth#625]
### Expected results
There should be different colour for tabs within menu on hovering than the menu tabs.
### Actual results
Same colour is used.
### Implementation/Solution Ideas
Add the colour to be used for tabs within the menu tabs. 
### Would you like to work on this
Yes

**Comment by Ploypiti** [comment]
Actually, it's different _tone_ of color, most site eg. facebook or Github use brighter/darker tone of color instead of a totally different color, although if you really want to use different color consider using secondary color as more than 2 color is not healthy for UI.

**Comment by harsh-jindal** [comment]
@Ploypiti I have used black colour with light opacity so it gives a nice effect and a contrast from the menu tabs.
You can have a look of it in the http://rawgit.com/fossasia/labyrinth/master/index.html#
I can change it if it is not good.
