### ISSUE TITLE
Labyrinth Logo in the contributors page is not good

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/labyrinth#633]
### Expected results
Should be similar to the one on the main page
### Actual results
It is different from the logo on the main page.
link: http://rawgit.com/fossasia/labyrinth/master/contributors.html
### Implementation/Solution Ideas
Change the logo to one on the main page.
### Would you like to work on this
Yes

**Comment by DNS-404** [comment]
@harsh-jindal I'm working on this. Already opened an issue for it. #631

**Comment by harsh-jindal** [comment]
Didn't See.
