### ISSUE TITLE
No hover property for language options in How to Play

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/labyrinth#638]
### Expected results
On hovering over the language colour should change.
link: http://rawgit.com/fossasia/labyrinth/master/howtoplay.html
### Actual results
No such change.
### Implementation/Solution Ideas
Add hover property.
### Would you like to work on this
Yes.

**Comment by harsh-jindal** [comment]
@niccokunzmann Where should I make changes in css for howtoplay.html?
Can I include it in howtoplay.html itself?

**Comment by niccokunzmann** [comment]
I think, the best css would be:
- One css for a common design
- One css for each file which is for the design of this file.

Currently, I do not know which file to change when I want to change css.

**Comment by Ploypiti** [comment]
@harsh-jindal stylesheet.css
> Where should I make changes in css for howtoplay.html?

**Comment by harsh-jindal** [comment]
Thanks @Ploypiti will make the changes there.
