### ISSUE TITLE
Cursor should change to hand when it's hovered over a button

### ISSUE THREAD

**Issue by DNS-404** [fossasia/labyrinth#643]
### Expected results
The cursor should change to hand when it's hovered over languages under "select your language" in how to play page.

### Actual results
It's staying as cursor.

### Steps to reproduce the issue
Go to http://rawgit.com/fossasia/labyrinth/master/howtoplay.html and hover over languages. Your cursor won't change to a hand.

### Would you like to work on this
Yes

**Comment by harsh-jindal** [comment]
@DNS-404 I'm already working on this.
Issue #638

**Comment by DNS-404** [comment]
Okay! Sorry my bad. 😅
