### ISSUE TITLE
On decreasing browser size on main page the logo overlaps with menu

### ISSUE THREAD

**Issue by PrP-11** [fossasia/labyrinth#649]
### Expected results
Logo and menu should not overlap
### Actual results
Logo and menu overlaps on decreasing brower size to about half and disapper on further decrease in size. 
![overlap](https://user-images.githubusercontent.com/30981465/35295794-24c95c9e-00a0-11e8-8a0f-7a6f79c8b088.png)

### Would you like to work on this
Yes

**Comment by himanshuc3** [comment]
Hola. 
By mistake I didn't see this Issue, so I made a similar PR.
I apologise.
