### ISSUE TITLE
Correct the wall

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/labyrinth#65]
### Expected results

When you look at the walls of the labyrinth, you see that the right wall overlaps over the left wall.
This is not intended. Please move the left border of the right wall to be at the same location as the left wall.

### Actual results

Here you can see the overlapping of the walls as it is  not possible in real life.
http://rawgit.com/fossasia/labyrinth/master/index.html

## Would you like to work on this

This is an issue for people contributing for the first time.
You can use Inkscape to edit the wall. The black pointer (F2) can be used to move points of edges.
We are here to help. If you like to work on this, please comment. We like to help you, so talk to us in the [chat](https://gitter.im/fossasia/labyrinth).

Hint: It seems like this is fixed for the walls without doors but not for the walls with doors

**Comment by duttaditya18** [comment]
This is now extremely difficult to do as all other tiles were made on the basis of the previous one which had wrong dimension.

We need to get a script or action going for this issue.

Does anyone wanna help?

**Comment by niccokunzmann** [comment]
@duttaditya18 That is technical debt increasing by itself so to say.

**Comment by DNS-404** [comment]
I would like to work on this.

**Comment by DNS-404** [comment]
😮 That would be really difficult indeed. @duttaditya18

**Comment by YashKumarVerma** [comment]
Solved in array of pull requests
