### ISSUE TITLE
Cursor should change to hand when hovered in select language menu in contributors page

### ISSUE THREAD

**Issue by PradumanPannu** [fossasia/labyrinth#650]
### Expected results
Cursor should change to hand when hovered on languages in contributors page 
### Actual results
Cursor changes to type(text) form when hovered

### Would you like to work on this
Yes

**Comment by harsh-jindal** [comment]
@PradumanPannu I'm already working on this issue.See issue no. #634

**Comment by PradumanPannu** [comment]
Issue #634 is related to adding hover property and giving proper spacing between language options. This issue is different. It is simply to change cursor to hand on the buttons.

**Comment by harsh-jindal** [comment]
@PradumanPannu That is covered in hover property.
