### ISSUE TITLE
Add feature to show Number of badges owned out of total  

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/labyrinth#655]
### Expected results
In the Your Badges (in the left side menu) should show the number of badges owned out of total 
### Actual results
Now it only shows the badges owned.Not the number.
### Implementation/Solution Ideas
Add a number counter for the badges.
### Would you like to work on this
Anyone can work on it

**Comment by harsh-jindal** [comment]
@himanshuc3 The side menu does not show the number of badges owned out of the total number.
The issue is to implement a feature to display the (no. of badges owned) : (total no. of badges)

**Comment by himanshuc3** [comment]
Ok. Got it. I will start implementing.

**Comment by niccokunzmann** [comment]
@himanshuc3 Can this be closed?

**Comment by niccokunzmann** [comment]
I added what can be done to improve the code quality to #103

**Comment by niccokunzmann** [comment]
From my view, this can be closed. We have the counter now. Please comment if you think otherwise so we can re-open.
