### ISSUE TITLE
Labyrinth Logo & Icon

### ISSUE THREAD

**Issue by Ploypiti** [fossasia/labyrinth#657]
### Expected results
Stable logo and icon for the game.
### Implementation/Solution Ideas
Header Logo;
![labyrinth logo](https://user-images.githubusercontent.com/32614202/35330581-9c7de2dc-0136-11e8-9059-464f0ef98de8.png)
Readme logo;
![labyrinth logo2](https://user-images.githubusercontent.com/32614202/35330665-dfbe702a-0136-11e8-8c9b-09b94d31c99e.png)
Icon;
![labyrinth icon](https://user-images.githubusercontent.com/32614202/35330705-057f2f8e-0137-11e8-94ad-5e9d22f1732d.png)

PR coming up ( ﾟ▽ﾟ)/
Also guys, UI guideline and logo are _not_ associated, but yeah it's cool if these two are matched, don't take it so seriously...
### Would you like to work on this
Obviously.

**Comment by duttaditya18** [comment]
> Would you like to work on this
Obviously.

😄

 The design is changing quite a bit. The UI Guideline by you suggested Abril Fatface for the heading. So are we changing that? You need to update us on that matter as well.

The design looks absolutely amazing! ❤️ I don't see any problem with that.

Really like your work!

**Comment by YashKumarVerma** [comment]
The design looks awesome !

**Comment by STEdirisuriya** [comment]
looks awesome

**Comment by Ploypiti** [comment]
Thanks!
@duttaditya18 The logo is _not_ heading, however, with logo, we won't need header anymore, except in the case of extra elements which could be added in the future, I want logo to be explicitly separated with normal header.
