### ISSUE TITLE
Create an HTML page for the how-to-play tutorial (HTML/CSS)

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/labyrinth#66]
### Expected results

On the web page, I would like to see some help button or link which leads to a page which shows me how to play the game.

### Actual results

Currently, we have this page: https://github.com/fossasia/labyrinth/blob/master/HOW-TO-PLAY.md
This is written in markdown.

## Would you like to work on this

You can convert [the page](https://github.com/fossasia/labyrinth/blob/master/HOW-TO-PLAY.md) to an HTML page and link to it from the index.html file.

This is an issue for people contributing for the first time.
We are here to help. If you like to work on this, please comment. We like to help you, so talk to us in the [chat](https://gitter.im/fossasia/labyrinth).

**Comment by Ploypiti** [comment]
@niccokunzmann Claiming.
