### ISSUE TITLE
Allow choosing game characters

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/labyrinth#68]
### Expected results

Before the game starts, we want to choose different characters to play with.
This is useful for the [GCI task][task].

### Actual results

Currently, we do not have any characters we can choose.

### Hints to solve

- [x] create a character
- [x] add the character to a folder
- [ ] link that folder in the task
- [ ] add a javascript file which loads characters from a list of characters
- [x] show the character on the tile it walks on

There is no need to do all of this at once.
Once we completed that, we can open up the GCI task for new contributors to the labyrinth.

[task]: https://github.com/fossasia/labyrinth/commit/abc31b31513f9b7e95ab46a1bb9203c86931fd14

**Comment by abishekvashok** [comment]
Can I do it?
Note: If any one wants to help me out, you are free to send me a message on gitter.

**Comment by niccokunzmann** [comment]
Yes, you and the other people can claim this task: https://github.com/fossasia/labyrinth/blob/master/tasks/enable-a-new-gci-task.md as this enables us to include one more GCI task into the system.

**Comment by YashKumarVerma** [comment]
@abishekvashok shall we work together on this one ?

**Comment by abishekvashok** [comment]
Sure

**Comment by abishekvashok** [comment]
@niccokunzmann is it required that the character walks thorough the door to the next room?

**Comment by niccokunzmann** [comment]
No, I do not think so. That makes it too complicated. Do you know the
games civilization or heroes of might and magic? Sometimes, they do not
have a relation between the ground and the figure walking on it. We do
not need that relation, I think.

**Comment by abishekvashok** [comment]
@niccokunzmann I have'nt played those games! My taste is on sporty games like need for speed editions and silent killers like assassin creed which feature some graphics and not isomteric tiles. 

However, I think we can have an approach where the character blinks from the current tile and appears in the next time at a descent transition time. What do you guys think?

**Comment by niccokunzmann** [comment]
Sounds good.

**Comment by abishekvashok** [comment]
@niccokunzmann done

**Comment by niccokunzmann** [comment]
I re-opened the issue since we do not have a menu where we can choose the characters.

- [ ]  link that folder in the task
- [ ] add a javascript file which loads characters from a list of characters

**Comment by abishekvashok** [comment]
@niccokunzmann on it.

**Comment by abishekvashok** [comment]
> add a javascript file which loads characters from a list of characters

can we do this is `player.js` itself?

**Comment by niccokunzmann** [comment]
Maybe, the character seems to be related to the player. If you think it gets too big and too unrelated to the player functionality, please move it to an other file. Understandability is key, there are metrics named "cohesion" and "coupling" which could help decide this.

**Comment by abishekvashok** [comment]
@niccokunzmann remaining solved in #174
