### ISSUE TITLE
Text size of version title do not match others in the menu

### ISSUE THREAD

**Issue by PrP-11** [fossasia/labyrinth#682]
### Expected results
The title Version should be of the same size as others in the menu
### Actual results
![version](https://user-images.githubusercontent.com/30981465/35380729-1f3053d2-01e0-11e8-8b9c-7352c2db8a4b.png)

### Would you like to work on this
Yes

**Comment by duttaditya18** [comment]
@PradumanPannu This was intentional. The Version is not as important as the other headings. So I made its font size smaller and lowered its opacity.

**Comment by YashKumarVerma** [comment]
@duttaditya18 I agree to this. It should remain like it is.

@PradumanPannu

**Comment by PrP-11** [comment]
@duttaditya18 Okay.
