### ISSUE TITLE
Some workaround for Bulky Clone ?

### ISSUE THREAD

**Issue by YashKumarVerma** [fossasia/labyrinth#685]
I don't know if others will agree to this, but cloning the game has become tedious, so is there any workaround which can somehow skip the audio files from cloning ? Or can we host the audios to some other branch ?

**Comment by niccokunzmann** [comment]
* We can delete all music which is from somehwere else and not from
    students
  * You can use git clone --depth=1 ... to only clone the last commits
    and see if that goes faster

**Comment by himanshuc3** [comment]
Hola people.
According to https://www.atlassian.com/blog/git/handle-big-repositories-git:
Solution proposed by @niccokunzmann would work. Although it would have been a better solution if the repo had very long history. For a repo having binary assests, this could be a better solution:
1. git clone
2. git config core.sparsecheckout true
3. Add folders that are needed explicitly, ignoring assets folders:
    echo src/ › .git/info/sparse-checkout
4. git read-tree -m -u HEAD

After the above, you can go back to use your normal git commands, but your work directory will only contain the folders you specified above.

**Comment by duttaditya18** [comment]
@niccokunzmann Very soon we'll have too many binaries, making this repository over the current limit of GitHub of 1GB. I really think we must host the music somewhere else.

**Comment by niccokunzmann** [comment]
Do you have a citation/source for this limit?
We can also remove all music which is not self-made by contributors. That makes it even smaller.
We can also host it in a different branch.

**Comment by duttaditya18** [comment]
@niccokunzmann https://help.github.com/articles/what-is-my-disk-quota/

The limit is quite rigid. And Git LFS is quite pricey.

**Comment by niccokunzmann** [comment]
I clicked through and I think, we are able to remove large files.
Some of the might be just in the git history. This explains how we can
remove certain files:
https://help.github.com/articles/removing-sensitive-data-from-a-repository/
There might be tricks to find the biggest files in the git history.

**Comment by niccokunzmann** [comment]
I think, there are almost no commits with just big files. If there are some, I do not know what happens.

**Comment by YashKumarVerma** [comment]
@niccokunzmann can we propose a new branch for static content? Or maybe for music?
