### ISSUE TITLE
Make menubar text aligned correctly.

### ISSUE THREAD

**Issue by STEdirisuriya** [fossasia/labyrinth#700]
### Expected results
Make menu-bar text aligned correctly.

### Actual results
![image](https://user-images.githubusercontent.com/33794760/35481670-d9413588-044d-11e8-9d2d-f10c32629966.png)
On the menu-bar the icon of labyrinth and "How to play" menu item with going. And small part of "select your language" menu item is not showing.

### Steps to reproduce the issue
Make text smaller.

### Would you like to work on this
nope

**Comment by Ploypiti** [comment]
It's working just fine here...
![image](https://user-images.githubusercontent.com/32614202/35493671-ae53e7ea-04e7-11e8-838d-fe3a79fe55ce.png)

**Comment by duttaditya18** [comment]
@Ploypiti It is because of different screen resolutions. The menu bar is messed up for me as well.

**Comment by himanshuc3** [comment]
I would be happy to solve this issue. 
Give me a day's time.

**Comment by duttaditya18** [comment]
@himanshuc3 Awesome!

**Comment by duttaditya18** [comment]
So I think this is done.

**Comment by niccokunzmann** [comment]
I also think this is done. Here we have screen shots: https://github.com/fossasia/labyrinth/pull/709#issuecomment-363045397
