### ISSUE TITLE
Labyrinth Logo overlapping the sidebar

### ISSUE THREAD

**Issue by himanshuc3** [fossasia/labyrinth#707]
### Expected results

![screen shot 2018-02-05 at 8 46 42 am](https://user-images.githubusercontent.com/19166045/35787032-3f196638-0a51-11e8-8b2c-e54bd3b9f9f5.png)

### Actual results

![screen shot 2018-02-05 at 8 44 45 am](https://user-images.githubusercontent.com/19166045/35787003-2036f014-0a51-11e8-88da-11e69549c9fd.png)

### Steps to reproduce the issue

Run labyrinth on localhost and reduce the width of the browser.

### Would you like to work on this

**Yes.**

**Comment by isuruAb** [comment]
@himanshuc3  how is the progress of this issue

**Comment by himanshuc3** [comment]
It is solved.
