### ISSUE TITLE
Clicking on the Logo should direct to the home page

### ISSUE THREAD

**Issue by iknoorjobs** [fossasia/labyrinth#713]
### Steps to reproduce the issue
Go to contributors page. Now there is no way to return back to the game except going back.

### Implementation/Solution Ideas
Clicking on the logo should direct to the home page with game.

### Would you like to work on this
Yes

**Comment by ashupednekar** [comment]
I'd like to fix  this issue

**Comment by duttaditya18** [comment]
Is this still not solved?

**Comment by iknoorjobs** [comment]
Yes

**Comment by duttaditya18** [comment]
@iknoorjobs Then why you closed it?
