### ISSUE TITLE
Adding Play/Pause feature in the Foreground

### ISSUE THREAD

**Issue by himanshuc3** [fossasia/labyrinth#714]
### Expected results
![screen shot 2018-02-06 at 5 02 24 pm](https://user-images.githubusercontent.com/19166045/35857989-cd758762-0b60-11e8-9bf0-caf29a25357a.jpg)

### Actual results
![screen shot 2018-02-06 at 5 11 50 pm](https://user-images.githubusercontent.com/19166045/35858001-d984b320-0b60-11e8-9ec4-dbadb7bb113d.png)

### Would you like to work on this
Yes. If approved.

**Comment by iknoorjobs** [comment]
@himanshuc3 Is this done?

**Comment by himanshuc3** [comment]
No.

**Comment by iknoorjobs** [comment]
Are you working on this or should I give it a try?

**Comment by himanshuc3** [comment]
Working on it. Although we could pair program.

**Comment by iknoorjobs** [comment]
Sure

**Comment by duttaditya18** [comment]
On it!
