### ISSUE TITLE
Clicking outside select character popup closes it

### ISSUE THREAD

**Issue by himanshuc3** [fossasia/labyrinth#727]
### Expected results
- Only closes on clicking on ok button or start button.

### Actual results
- Modal/popup goes down on clicking outside modal box.

![screen shot 2018-02-11 at 8 24 25 pm](https://user-images.githubusercontent.com/19166045/36074681-973862f2-0f69-11e8-8001-2f9bf398b31d.png)
### Implementation/Solution Ideas
- 2 possible solutions: Either make modal manually without help of sweetalert2 library or find a hack to override sweetalert2 behaviour( maybe its docs would help)

### Would you like to work on this
Yes.

Edit: Setting backdrop: true does the trick but induces more problems.

**Comment by duttaditya18** [comment]
@himanshuc3 That is easily fixable. Read the SweetAlert2 Docs here : https://sweetalert2.github.io/

Just set `allowOutsideClick`, `allowEscapeKey`, `allowEnterKey` to false.

**Comment by Rishabh570** [comment]
@duttaditya18 @himanshuc3 I would like to work on it.

**Comment by Rishabh570** [comment]
@duttaditya18 I've opened a PR for it.
