### ISSUE TITLE
[WEEKATHON] Correct Intellectual Property of WEEKATHON Website

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/labyrinth#732]
### Expected results

In the WEEKATHON folder, I would like to apply the AGPL. to be sure we are allowed to use the code.

### Actual results

We are not allowed to apply the AGPL.
We might not even be allowed to use some of the files.

> Actually it's a part of some sort of bundle I bought from envato last month for my project lol. sorry for late reply, it's Saturday night :P - @Ploypiti https://github.com/fossasia/labyrinth/pull/730#issuecomment-366436169

And 

> You may not copy, distribute, modify, publish or make derivative works of any of our IP in any way not expressly authorised by these terms. - https://sites.envato.com/terms

Which is clearly in contrast to AGPL.

### (1) Use of the site and contributions to the site made by @Ploypiti in Ploypiti's repository

- [x] revert the pull request #730
- [x] add WEEKATHON / weekathon.html, redirecting to the site hosted by @Ploypiti ([Example](https://github.com/CoderDojoPotsdam/CoderDojoPotsdam.github.io/blob/master/hpi/index.html))
- [x] use a url-shortener for the website https://rawgit.com/fossasia/labyrinth/master/WEEKATHON/weekathon.html to advertise the labyrinth.

### (1.1) in the future we can use software with Intellectual Property rights which are compatible with AGPL.

There is no need to host this here. @Ploypiti has shown collaoration and as long as we go though this repository - https://rawgit.com/fossasia/labyrinth/master/WEEKATHON/weekathon.html - no harm will be done: 
1. We can still change and improve the site at @Ploypiti's repository.
2. We can still change the content here, if someone is willing to create a new site, the site by @Ploypiti goes down or @Ploypiti does not respond any more.

### (1.2)

@Ploypiti Shows the express consent of the creators of the files that these files might be licensed under AGPL which will effectively remove their right to charge for them.

### (1.3)

The licenses for these files are provided and evident:

- [ ] WEEKATHON/css/et-line-icons.css
- [ ] css/responsive.css
- [ ] css/style.css
- could be GPLv2
  - [ ] fonts/et-line.eot
  - [ ] fonts/et-line.ttf
  - [ ] fonts/et-line.woff
- [ ]  WEEKATHON/js/jquery.themepunch.revolution.min.js
- [ ]  WEEKATHON/js/main.js
- [ ] WEEKATHON/js/skrollr.min.js
- [ ] WEEKATHON/js/wow.min.js

### Further Reading

Licenses are the contracts to grant the rights (intellectual property rights) to a set of unknown people.
Here is a quote:

> Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the **rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell** copies of the Software, and to permit persons to whom the Software is furnished to do so [...] - https://opensource.org/licenses/MIT

>    This program is free software: you can **redistribute it and/or modify**
>    it under the terms of the GNU Affero General Public License as
>    published by the Free Software Foundation, either version 3 of the
>    License, or (at your option) any later version. - https://opensource.org/licenses/AGPL-3.0

**Comment by Ploypiti** [comment]
First of all,
> 1.The Regular License grants you, the purchaser, an ongoing, non-exclusive, worldwide license to make use of the digital work (Item) you have selected. Read the rest of this license for the details that apply to your use of the Item, as well as the FAQs (which form part of this license).
2.You are licensed to use the Item to create one single End Product for yourself or for one client (a “single application”), and the End Product can be distributed for Free.
3.An End Product is one of the following things, both requiring an application of skill and effort.
(a)For an Item that is a template, the End Product is a customised implementation of the Item.
For example: the item is a website theme and the end product is the final website customised with your content.
(b) For other types of Item, an End Product is a work that incorporates the Item as well as other things, so that it is larger in scope and different in nature than the Item.
For example: the item is a button graphic and the end product is a website. See the FAQs for examples and information about End Products and the single application requirement.
4.You can create one End Product for a client, and you can transfer that single End Product to your client for any fee. This license is then transferred to your client.
5.You can make any number of copies of the single End Product, as long as the End Product is distributed for Free.
6.You can modify or manipulate the Item. You can combine the Item with other works and make a derivative work from it. The resulting works are subject to the terms of this license. You can do these things as long as the End Product you then create is one that’s permitted under clause 3.
For example: You can license a flyer template, include your own photos, modify the layout and get it printed to promote your event.

Second, I'M ON A VACATION WIHOUT LAPTOP MAN, I can't even send another PR.

**Comment by niccokunzmann** [comment]
I think that you might be frustrated because you put a lot of work in you like to see valued and used. Furthermore, you might fear that if you do nothing, your work is lost.

I woke up this morning and could not get to sleep because these licenses do not seem to be usable under AGPL/GPL:

> The Regular License grants you, the purchaser, an ongoing, non-exclusive, worldwide license to make use of the digital work (Item) you have selected.

I do not see that I am allowed to use the files you purchased. 

---

There is a way in which both you and I are satisfied and also the provider of the files. I would like to go this way and not decide it over your head or use maintainer privileges to do so.

I imagine this in #733:
- Your site is used.
- We host it at your place

So, you are the "owner", satisfying the requirements of their license, still and we can use all you did and provide patches.

Would that be ok for you? What else is on your heart? Let's focus on the requirements for a solution which would be optimal for you.

**Comment by niccokunzmann** [comment]
> and the End Product can be distributed for Free.

is interesting. I think, for Free means free of charge. I do not think that it means "free software".

>  one single End Product

This is something I do not understand: Websites will be improved all the time. There are several versions each time one end product. Once it is forked, there are many end products.

AGPL: 
> use pieces of it in new free programs

this license:

> You can make any number of copies of the single End Product, as long as the End Product is distributed for Free.

This might conflict with  AGPL:

> you have the freedom to distribute copies of free software (and charge for them if you wish)

---

I think, "for free" means free of charge and not that one can use it without restrictions.

**Comment by Ploypiti** [comment]
I contacted them and I think they're totally okay with this, (and yes I informed them about licenses overlap) note that >50% of the site is from Envato.

>**Regular licenses** are meant for items used in end products that are **accessible without extra fees.** In the case of websites, it applies to sites which visitors can access **free of charge.** This includes eCommerce sites, as visitors pay for the physical products and services available, and **not actually for access to the site.**

We can discuss this again whenever you want to charge for accessing labyrinth. To be honest, my responsibility is beyond whatever happens after my job is done.

For a better depiction;
![untitled](https://user-images.githubusercontent.com/32614202/36364641-d8514e52-1577-11e8-8d94-5170df20d33a.png)

In case you're still concerning about this the site is hosted at https://ploypiti.github.io/labyrinth/WEEKATHON/weekathon.html.

**Comment by niccokunzmann** [comment]
Currently, we have this link: https://rawgit.com/fossasia/labyrinth/master/WEEKATHON/weekathon.html
Redirecting to your site.
We can use your site as the advertisement by using the labyrinth redirect link.

It is not about me charging. The AGPL allows it. If we create an app for the app store, we can have a  free version and a support+pay version. However, this is not possible if the Envato code is shipped with it. Thus, the Envato license must be shipped with the code it applies to. Otherwise people will unknowingly and unwillingly violate the license. I am also not sure if it is AGPL-conform to ship the code with this restriction.

**Comment by duttaditya18** [comment]
@niccokunzmann So we should contribute to @Ploypiti repo?

Also, what is the next step? Should we start putting info on the website? Or should we wait for the License mess to get sorted?

**Comment by niccokunzmann** [comment]
From my view, we can start contributing the content to Ploypiti
<https://github.com/ploypiti>'s repository.

**Comment by duttaditya18** [comment]
@niccokunzmann Cool!

**Comment by Ploypiti** [comment]
Can we close this?

**Comment by niccokunzmann** [comment]
@Ploypiti Sure, solution 1.1 is implemented. Is it ok if we contribute to your site?

**Comment by Ploypiti** [comment]
Yeah, go on.
