### ISSUE TITLE
Remove the "Hints for GCI-Students" Section

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/labyrinth#741]
We can remove the section "Hints for GCI-Students":

- because GCI is over.
- because this is a copy from the tasks

To close this:

- [ ] remove the heading from the outline
- [ ] remove the section including "Solve an Issue"

**Comment by duttaditya18** [comment]
Should we maybe put it in a different Markdown file titled "GCI" or something?

**Comment by niccokunzmann** [comment]
We can do this. It was a copy from the tasks https://github.com/fossasia/labyrinth/tree/master/tasks so, it is duplicated documentation. What do you think?

**Comment by xeon-zolt** [comment]
@niccokunzmann shouldn't we change it to guide for contributes ??

**Comment by niccokunzmann** [comment]
@xeon-zolt In #726, we have these tasks as issue templates all added to the contributing file.
