### ISSUE TITLE
[WEEKATHON] Promote the Weekathon

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/labyrinth#743]
The dates are set. Now, we can invite other people to join us.

### How to use the Feature

We can write letters, mails, put up posters, ...
to promote the weekathon and get people to know about it.

### How the Feature Improves the Game

This will bring more people to the weekathon

### Implementation/Solution Ideas

We can promote it here:
- [ ] fossasia mailing list
- [ ] fossasia conference
- [ ] gci website
- [ ] fossasie gitter
- [ ] the artist #722 
- [ ] universities - basic levels
- [ ] local schools
- [ ] techologiestiftung
- [ ] open tech school
- [ ] JS user groups
- [ ] game museums
- CoderDojo
  - [ ] Foundation
  - [ ] local groups
  - [ ] slack
  - [x] facebook
  - [ ] Twitter

### Would you like to work on this

yes, with your help even more.

Related: #742 #552

**Comment by abishekvashok** [comment]
Status @niccokunzmann

**Comment by niccokunzmann** [comment]
Can be closed.
