### ISSUE TITLE
Replace rawgit for preview links

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/labyrinth#761]
Rawgit is down. We can not use it to create a preview link. We need a replacement for it that allows us to generate a preview link easly.

- Please search for websites which allow us to replace this site.
- Or add a description on how to preview using github pages (not optimal, as we would like people to use other branches than master and have the PRs document the current state)

**Comment by niccokunzmann** [comment]
This blog post describes how to create deploy links as comments on a pull request: https://damien.pobel.fr/post/github-api-from-travisci/

There must be a way how we can deploy a website to any place easily - it only needs to be there for a day or two.

**Comment by abishekvashok** [comment]
https://gitcdn.xyz

**Comment by abishekvashok** [comment]
https://raw.githack.com

**Comment by YashKumarVerma** [comment]
Do we still need rawgit previews?
