### ISSUE TITLE
move deploy.sh to scripts folder

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/labyrinth#778]
Please 

- [ ] move the deploy.sh file to the scripts folder as this is where the files are which we use to execute.
- [ ] make it executable
- [ ] also change the .travis.yml file

**Comment by ammarbinfaisal** [comment]
>  make it executable

@niccokunzmann shud I write a separate script to modify its permissions so that it can be executed as `./scripts/deploy.sh`.

**Comment by niccokunzmann** [comment]
If you have linux, you do not need that.
Do

    chmod +x deploy.sh

Then, move it, commit --all and you are done.

**Comment by ammarbinfaisal** [comment]
:man_facepalming: Ive already done that,  
I deploy in .travis.yml has to be changed to `././scripts/deploy.sh`. currentl it is `bash ./deploy.sh`  
thta was very foolish of me, sorry about that.
