### ISSUE TITLE
Update Maintainers' Section

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/labyrinth#783]
Please update the maintainers' section the bottom of the README file.

- [ ] add the missing maintainers
- [ ] Add a text that if you like to become an admin, you should request to join https://github.com/orgs/fossasia/teams/labyrinth-admins/members

- [x] @YashKumarVerma 
- [ ] @saarthakchats 
- [ ] @abishekvashok

**Comment by parammittal16** [comment]
Hi @niccokunzmann  Can I work on this ?

**Comment by YashKumarVerma** [comment]
Sure @parammittal16 .
