### ISSUE TITLE
Left navigation slider only opens and doesnt get close

### ISSUE THREAD

**Issue by ammarbinfaisal** [fossasia/labyrinth#793]
### Present behaviour
Clicking on the nav burger opens the navigation slider but clicking on it after that doesnt closes it but scrolls the page to the top

### Expected behaviour
Clicking on the nav burger should toggle the nav slider - close it if it is open and open it if it is closed.

**My screen size:** 1920 x 1080
**Browser:** Chrome 69
And I'd like to help in fixing this

**Comment by YashKumarVerma** [comment]
Good to know you want to fix this. Feel free to ask for help if needed.
