### ISSUE TITLE
Weird hover over "select your language" in the navbar

### ISSUE THREAD

**Issue by ammarbinfaisal** [fossasia/labyrinth#796]
![hoverbug](https://user-images.githubusercontent.com/30975614/47959756-36e7e380-e012-11e8-95d8-da4f6c174ee6.gif)
## Present behaviour
Hover on the parent of "select your language" element turns the parent's bg light green and then moving to the text turns it bg light green and triggers the dropdown
## Expected behaviour
Hovering on the parent itself should do all that

**Comment by STEdirisuriya** [comment]
I am working on this
