### ISSUE TITLE
delete how-to-play.md

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/labyrinth#81]
### Expected results

When I want to know how to play the game, I would like to use the HTML version of the game.

### Actual results

Currently, we use the markdown version.

### Steps to reproduce the issue

- https://github.com/fossasia/labyrinth/blob/master/HOW-TO-PLAY.md
- https://github.com/fossasia/labyrinth/blob/master/howtoplay.html

Also see the README.md file - there is a link

TODO:
- [x] change the link in the reamd
- [ ] delete the markdown file

**Comment by YashKumarVerma** [comment]
Closed.

**Comment by niccokunzmann** [comment]
The "HOW-TO-PLAY.md" file is still there, please check: https://github.com/fossasia/labyrinth/blob/master/HOW-TO-PLAY.md

**Comment by YashKumarVerma** [comment]
anyone working on it ? or shall i ?

**Comment by duttaditya18** [comment]
@YashKumarVerma Give newcommers a chance.

**Comment by YashKumarVerma** [comment]
@duttaditya18 that's why i asked before sending a pr 😆

**Comment by niccokunzmann** [comment]
You can also delete it. Noone came. Better to clean up soon.

**Comment by duttaditya18** [comment]
@niccokunzmann #119 fixes this.
