### ISSUE TITLE
Adding a timer.

### ISSUE THREAD

**Issue by STEdirisuriya** [fossasia/labyrinth#815]
When we need it to be a competition, we need a points system and a timer. 
I am going to add a timer. 

I am working on this!

**Comment by STEdirisuriya** [comment]
@niccokunzmann Could you please tag this as a new feature if it's good?

**Comment by YashKumarVerma** [comment]
We can no doubt add a timer but what will be the use? It's not competitive i guess. THere

**Comment by YashKumarVerma** [comment]
Really a nice idea! Thanks 👍

**Comment by YashKumarVerma** [comment]
Feature Added. :champagne: 
Closing.
