### ISSUE TITLE
Tasks not listed on GCI Site

### ISSUE THREAD

**Issue by YashKumarVerma** [fossasia/labyrinth#84]
### Expected results
The tasks listed here on Repo should be on GCI site as well. 

### Actual results
The tasks are not listed on GCI site 

### Steps to reproduce the issue
Mentors must add them 😋

## Would you like to work on this
Can't. 😂

**Comment by niccokunzmann** [comment]
They are added, we need to wait for the organization administrators to approve them.

**Comment by YashKumarVerma** [comment]
sure thing @niccokunzmann

**Comment by duttaditya18** [comment]
This is indeed, really needed!

**Comment by YashKumarVerma** [comment]
@duttaditya18 :rofl:

**Comment by duttaditya18** [comment]
😄
