### ISSUE TITLE
Add a good looking alert box on winning.

### ISSUE THREAD

**Issue by duttaditya18** [fossasia/labyrinth#85]
### Expected results
A good looking alert box on winning. (like SweetAlert)

### Actual results
A normal JS alert box.

## Would you like to work on this
Yes.

**Comment by duttaditya18** [comment]
@niccokunzmann Can I use an open source library like SweetAlert2?

**Comment by YashKumarVerma** [comment]
@duttaditya18 I think we can add them. I asked @niccokunzmann about jquery so he said yes as far as it is being added systematically. (in proper directory)

**Comment by duttaditya18** [comment]
@YashKumarVerma Can I use SweetAlert2?

**Comment by duttaditya18** [comment]
@YashKumarVerma I have added a good looking alert using SweetAlert2. However no one would be too happy about an extra dependency. Please suggest something.

https://rawgit.com/duttaditya18/labyrinth/master/index.html
