### ISSUE TITLE
Feature Request : Dedicated Branch for Media 

### ISSUE THREAD

**Issue by YashKumarVerma** [fossasia/labyrinth#854]
NEED ![GitHub repo size in bytes](https://img.shields.io/github/repo-size/fossasia/labyrinth.svg) 
---
 - Currently, the size of the repository is about 150mb , and to even do a minor change in game, or to add a tile, or levels, a developer has to clone a whooping 150mbs. 
 - As the game is updated very frequently, and majority of the developers are first time contributers, a good fraction of people clone the repository again and again to do a change.

---

PROPOSED SOLUTION :  ***71% reduction in size***
---
 - A dedicated branch for media files (audio) will reduce the size by ~100mb (as of now), ***71% reduction in size***
- As the game progresses, the size of code does not increase as steeply increase the repo size as compared to the addition of music .

---
TODO
---
- [ ] Change Links in game
- [ ] Configure branch **media**
- [ ] Incorporate changes in Documentation
---

---
@niccokunzmann @abishekvashok @saarthakchats and other contributors' opinion are welcomed.

**Comment by STEdirisuriya** [comment]
@YashKumarVerma Is it reduces the size? 
`A dedicated branch for media files (audio) will reduce the size by ~100mb (as of now), 71% reduction in size` 
I am not sure. I think it's not to add in a dedicated branch in the same, it needs to add in another repo. 

We can add tiles, audio files etc. which needs a huge space in another repo separately. We can tell contributors to if they are adding some files like aforesaid, add them into that repo from the window easily. I told that they can drag the files and drop them into our new repo, it will make a PR automatically. After they can clone only this repo and add links to tile in files in this repo.

What do you think?

**Comment by abishekvashok** [comment]
> PROPOSED SOLUTION : 71% reduction in size
A dedicated branch for media files (audio) will reduce the size by ~100mb (as of now), 71% reduction in size
As the game progresses, the size of code does not increase as steeply increase the repo size as compared to the addition of music .

This would make the game non-working and stupious, its not how git branches should be used.

**Comment by abishekvashok** [comment]
Instead ask them to do a shallow clone instead, the size of the repo increases as many files are untrackable by git. For it use:
`git clone https://github.com/fossasia/labyrinth --depth=1`

It reserves the commit history to the last one though, which is not a problem 99.9% times, and for the rest .01% increase the depth to the commit you want.

**Comment by abishekvashok** [comment]
Also, 150 mb is not a large size in my opinion

**Comment by pythongiant** [comment]
I propose a better solution. If people have slow internet, we can have them download a compressed version of the code.

**Comment by abishekvashok** [comment]
Again adding to shallow clone,
https://marco-steinhaeuser.de/use-shallow-clone-to-reduce-the-download-size-of-a-github-repository.html
https://medium.com/@wdyluis/git-gc-and-git-shallow-clone-360aade9403e

**Comment by YashKumarVerma** [comment]
Thanks for your openions @abishekvashok @pythongiant @STEdirisuriya.

I think the shallow clone is the best solution as proposed by @abishekvashok and the links were very helpful too. Thanks for your help.

Closing as better Options in Hand.
