### ISSUE TITLE
Spelling Mistakes in Pull Requests Template.

### ISSUE THREAD

**Issue by niteshkumarniranjan** [fossasia/labyrinth#878]
## Expected Behavior
Should be no spelling mistakes.

## Current Behavior
There are some spelling mistakes.

## Possible Solution
Correct those.

## Steps to Reproduce (for bugs)
https://github.com/fossasia/labyrinth/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Want to work on it**
Yes

**Comment by YashKumarVerma** [comment]
Would you like to work on it ? If possible, please provide the instances so that it can be easy to remove them.
