### ISSUE TITLE
Create icon for labyrinth

### ISSUE THREAD

**Issue by razetime** [fossasia/labyrinth#88]
As of now, the labyrinth has the default icon for rawgit.com as its logo.
We have to design a logo for the labyrinth which represents it as a whole

We'd like some ideas and recommendations on how you'd like the logo to look, and how you will represent this project.

**Comment by razetime** [comment]
We could have a Minotaur as the logo, because a labyrinth was constructed by the Greek King Minos ad his architect Daedalus to contain the Minotaur. You are the minotaur in this gmae, and you are moving through the labyrinth to find your goals.

**Comment by yashGnius** [comment]
u r right

**Comment by saarthakchats** [comment]
Working on it!

**Comment by niccokunzmann** [comment]
@saarthakchats If you need any help, we are here and in the chat. Is there any progress, please share it.

**Comment by saarthakchats** [comment]
@niccokunzmann 
What should be the dimensions and after I have made it, where do I add it?

**Comment by niccokunzmann** [comment]
@saarthakchats This is an .ico file, they have different resolutions in one file. I think, 48x48 is enough. But you can choose.
