### ISSUE TITLE
Add music to blood tile

### ISSUE THREAD

**Issue by AirWolfXD** [fossasia/labyrinth#890]
## Expected Behavior

My blood tile will have a sound effect
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

I am doing Google Code-In 2018
## Your Environment

* Browser Name and version:
* Link to your project:
* Machine Configuration: Ram, Graphics Memory

**Comment by YashKumarVerma** [comment]
Consider following the template from next time.
