### ISSUE TITLE
Character changes to contributors on language change but still opens Character page.

### ISSUE THREAD

**Issue by niteshkumarniranjan** [fossasia/labyrinth#895]
## Expected Behavior
Character link should not change the link text to contributors on language switch.

## Current Behavior
Character changes to contributors on language change but still opens Character page.

## Possible Solution
To not change Character's link text to contributors.

## Steps to Reproduce (for bugs)
https://youtu.be/Xd66OyTF_Rw

## Context
Opens wrong link

**Comment by rajdeepbharati** [comment]
Can I work on this issue?

**Comment by niteshkumarniranjan** [comment]
@rajdeepbharti Sure go ahead.
