### ISSUE TITLE
Buttons and Links on sidebar doesn't works until game isn't started

### ISSUE THREAD

**Issue by niteshkumarniranjan** [fossasia/labyrinth#896]
## Expected Behavior
Button and Link should respond to clicks in any state

## Current Behavior

Buttons and Links on sidebar doesn't works until game isn't started

## Steps to Reproduce (for bugs)

1. Visit http://labyrinth-game.surge.sh/
2. Open sidebar
3. Try to click on a link or button

## Context
Its annoying if something is working and its not working at a same it.

## Your Environment

* Browser Name and version:
* Link to your project:
* Machine Configuration: Ram, Graphics Memory

**Comment by YashKumarVerma** [comment]
Closing in favor of #835
