### ISSUE TITLE
add a new character

### ISSUE THREAD

**Issue by gaurang7goel** [fossasia/labyrinth#923]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Browser Name and version:
* Link to your project:
* Machine Configuration: Ram, Graphics Memory

**Comment by YashKumarVerma** [comment]
Labyrinth has a set of Issue Templates to standardize the development.

Consider using them. That can be found at 
https://github.com/fossasia/labyrinth/tree/master/.github/ISSUE_TEMPLATE

Thanks for your contribution to the community.
