### ISSUE TITLE
Feature Request : Teleport

### ISSUE THREAD

**Issue by YashKumarVerma** [fossasia/labyrinth#937]
### How to use the Feature
A simple teleport button in the sidebar which will (**_teleport_**) the player directly by taking input in form on 

> UP,UP,DOWN,DOWN,RIGHT
(output of #936 is input here)

### How the Feature Improves the Game
Since Labyrinth is an actively developed game (1500 commits achieved), it often takes a lot of time for developers/students to find the tiles to observe the changes (see new tile, new animation, new functionality, new music, new features etc). 

The PR template was updated in #934 to add **_PATH TO TILE_** in the template itself. This new feature would help achieve the same in case of distant tiles by taking the user there. 

### Implementation/Solution Ideas
- Take input from user
- Simulate key presses

### Would you like to work on this
Open to All.

Followup of #936

**Comment by YashKumarVerma** [comment]
If other contributors need ideas for new features, message on channel.

**Comment by AppleC4T** [comment]
@YashKumarVerma Can I work on this feature even if I completed the "Labyrinth: Add a new feature" task?

**Comment by YashKumarVerma** [comment]
> @YashKumarVerma Can I work on this feature even if I completed the "Labyrinth: Add a new feature" task?

Why not ! Sure ! Go ahead !

**Comment by YashKumarVerma** [comment]
> Ok, I’ll work on it!

#936 will provide the output string
