### ISSUE TITLE
Feature Request: SVG upload tests

### ISSUE THREAD

**Issue by YashKumarVerma** [fossasia/labyrinth#944]
### How to use the Feature
The script will automatically check size(dimensions) of images uploaded in**_tiles/_**  directory and will stop the Travis build if the size is not fit for the game.

### How the Feature Improves the Game
Ensures the game is playable

### Implementation/Solution Ideas
-See for changes in directory/process all the files.
- Break if an image with the wrong dimensions found.

### References
- See readme for dimensions

**Comment by saarthakchats** [comment]
@abishekvashok 
https://github.com/abishekvashok/img_checker
Does this support svg image dimension checks?

**Comment by saarthakchats** [comment]
If yes then I can solve this issue

**Comment by abishekvashok** [comment]
Yes it does

**Comment by saarthakchats** [comment]
Okay, I am working on it then
