### ISSUE TITLE
Feature Request : Script to remove unwanted files from deploy

### ISSUE THREAD

**Issue by YashKumarVerma** [fossasia/labyrinth#948]
### How to use the Feature
The script will automatically remove files which are not required from deploy.

### How the Feature Improves the Game
Ensures that game deploys are light

### Implementation/Solution Ideas
- Using readymade script

### Reference
https://github.com/YashKumarVerma/Clean-Deploy
https://travis-ci.com/YashKumarVerma/Clean-Deploy/jobs/161130039

**Comment by Ryan10145** [comment]
I would like to work on this.

**Comment by YashKumarVerma** [comment]
Sure . Are you using the script ?

**Comment by YashKumarVerma** [comment]
Good Work @Ryan10145
