### ISSUE TITLE
Added a character

### ISSUE THREAD

**Issue by RahulMetre03** [fossasia/labyrinth#955]
Description
Added a new CHARACTER 'Mario'

Implementation Plan
 Step 1:Added a image with proper dimensions
 Step 2:Updated the gui.js file
 Step 3:Added a new character

Closing Criteria
 Criterion 1:The character is available for a player to begin with the game
 Criterion 2:All the details are filled properly

**Comment by abishekvashok** [comment]
Can you please fill this up?

**Comment by RahulMetre03** [comment]
Okay! @abishekvashok

**Comment by RahulMetre03** [comment]
Its done @abishekvashok
